/*
 *  Survey:           NHANES 1 Epidemiologic Followup Study
 *  Years:            1987


*/




DATA D_n87int;
   INFILE 'z:\Data\Esophagus\NHEFS\TEMP\n87int.txt' LRECL = 2000 MISSOVER;
 INPUT @1    SEQNO    $CHAR5.
        @6    BLANK1   $CHAR2.
        @8    PREVINT  $CHAR2.
        @10   SUBSEX   $CHAR2.
        @12   TRACSTAT $CHAR2.
        @14   GRRSLTMO $CHAR6.
        @14   RSLTMO   $CHAR2.
        @16   RSLTDAY  $CHAR2.
        @18   RSLTYR   $CHAR2.
        @20   AGENOW   $CHAR2.
        @22   BASERSLT $CHAR2.
        @24   DCRECD   $CHAR2.
        @26   GRDEATHM $CHAR6.
        @26   DEATHMO  $CHAR2.
        @28   DEATHDAY $CHAR2.
        @30   DEATHYR  $CHAR2.
        @32   BLANK2   $CHAR44.
        @76   ARTHECF  $CHAR2.
        @78   GOUTECF  $CHAR2.
        @80   HEARTATT $CHAR2.
        @82   HEARTOTH $CHAR2.
        @84   BYPASECF $CHAR2.
        @86   PACEECF  $CHAR2.
        @88   STROKE   $CHAR2.
        @90   DIABETES $CHAR2.
        @92   BLOODPRE $CHAR2.
        @94   BPMEDECF $CHAR2.
        @96   BROKENHI $CHAR2.
        @98   CANCER   $CHAR2.
        @100  BRCANCER $CHAR2.
        @102  KIDNEYIF $CHAR2.
        @104  CATARECF $CHAR2.
        @106  LIVARECF $CHAR2.
        @108  WORKIF   $CHAR2.
        @110  RETIREIF $CHAR2.
        @112  MOMALIF  $CHAR2.
        @114  DADALIF  $CHAR2.
        @116  SMOKSTAT $CHAR2.
        @118  LIVBRTH1 $CHAR2.
        @120  PREGIF   $CHAR2.
        @122  UTERUSIF $CHAR2.
        @124  OVARYIF  $CHAR2.
        @126  PERIODIF $CHAR2.
        @128  HORMONES $CHAR2.
        @130  BCPILLIF $CHAR2.
        @132  BCPILL25 $CHAR2.
        @134  GRIDATEM $CHAR6.
        @134  IDATEMM  $CHAR2.
        @136  IDATEDAY $CHAR2.
        @138  IDATEYR  $CHAR2.
        @140  GRCFMONT $CHAR6.
        @140  CFMONTH  $CHAR2.
        @142  CFDAY    $CHAR2.
        @144  CFYEAR   $CHAR2.
        @146  GREXAMMO $CHAR6.
        @146  EXAMMO   $CHAR2.
        @148  EXAMDAY  $CHAR2.
        @150  EXAMYR   $CHAR2.
        @152  GRBIRTHM $CHAR6.
        @152  BIRTHMO  $CHAR2.
        @154  BLANK3   $CHAR2.
        @156  BDATE2   $CHAR2.
        @158  AGEEXAM  $CHAR2.
        @160  AGEIF    $CHAR2.
        @162  AGECF    $CHAR2.
        @164  AGECONT  $CHAR2.
        @166  ELIGECF  $CHAR2.
        @168  GRCONTMO $CHAR6.
        @168  CONTMO   $CHAR2.
        @170  CONTDAY  $CHAR2.
        @172  CONTYR   $CHAR2.
        @174  EFVIT    $CHAR2.
        @176  QDISIF   $CHAR2.
        @178  IFVIT    $CHAR2.
        @180  QDISECF  $CHAR2.
        @182  QVERSION $CHAR2.
        @184  REVRACE  $CHAR2.
        @186  PRELA    $CHAR2.
        @188  BLANK4   $CHAR5.
        @193  RELATOS  $CHAR2.
        @195  BLANK5   $CHAR90.
        @285  LIVEARRG $CHAR2.
        @287  BLANK6   $CHAR50.
        @337  SDIENRHM $CHAR2.
        @339  PRXLIVWD $CHAR2.
        @341  PRXVISTD $CHAR2.
        @343  NHCONTU  $CHAR2.
        @345  SAMENH   $CHAR2.
        @347  NUMSLIVE $CHAR2.
        @349  GRLGTHAL $CHAR4.
        @349  LGTHALNE $CHAR2.
        @351  LGTHUNIT $CHAR2.
        @353  GRRELATO $CHAR26.
        @353  RELTOS1  $CHAR2.
        @355  RELTOS2  $CHAR2.
        @357  RELTOS3  $CHAR2.
        @359  RELTOS4  $CHAR2.
        @361  RELTOS5  $CHAR2.
        @363  RELTOS6  $CHAR2.
        @365  RELTOS7  $CHAR2.
        @367  RELTOS8  $CHAR2.
        @369  RELTOS9  $CHAR2.
        @371  RELTOS10 $CHAR2.
        @373  RELTOS11 $CHAR2.
        @375  RELTOS12 $CHAR2.
        @377  RELTOS13 $CHAR2.
        @379  GRRELSEX $CHAR26.
        @379  RELSEX1  $CHAR2.
        @381  RELSEX2  $CHAR2.
        @383  RELSEX3  $CHAR2.
        @385  RELSEX4  $CHAR2.
        @387  RELSEX5  $CHAR2.
        @389  RELSEX6  $CHAR2.
        @391  RELSEX7  $CHAR2.
        @393  RELSEX8  $CHAR2.
        @395  RELSEX9  $CHAR2.
        @397  RELSEX10 $CHAR2.
        @399  RELSEX11 $CHAR2.
        @401  RELSEX12 $CHAR2.
        @403  RELSEX13 $CHAR2.
        @405  NUMSLVED $CHAR2.
        @407  GRLGTHA2 $CHAR4.
        @407  LGTHALN2 $CHAR2.
        @409  LGTHUNT2 $CHAR2.
        @411  GRRELDOS $CHAR24.
        @411  RELDOS1  $CHAR2.
        @413  RELDOS2  $CHAR2.
        @415  RELDOS3  $CHAR2.
        @417  RELDOS4  $CHAR2.
        @419  RELDOS5  $CHAR2.
        @421  RELDOS6  $CHAR2.
        @423  RELDOS7  $CHAR2.
        @425  RELDOS8  $CHAR2.
        @427  RELDOS9  $CHAR2.
        @429  RELDOS10 $CHAR2.
        @431  RELDOS11 $CHAR2.
        @433  RELDOS12 $CHAR2.
        @435  GRRELDSX $CHAR24.
        @435  RELDSX1  $CHAR2.
        @437  RELDSX2  $CHAR2.
        @439  RELDSX3  $CHAR2.
        @441  RELDSX4  $CHAR2.
        @443  RELDSX5  $CHAR2.
        @445  RELDSX6  $CHAR2.
        @447  RELDSX7  $CHAR2.
        @449  RELDSX8  $CHAR2.
        @451  RELDSX9  $CHAR2.
        @453  RELDSX10 $CHAR2.
        @455  RELDSX11 $CHAR2.
        @457  RELDSX12 $CHAR2.
        @459  MARRSTAT $CHAR2.
        @461  SUBJRACE $CHAR2.
        @463  BLANK7   $CHAR30.
        @493  HISPANIC $CHAR2.
        @495  DOINGMST $CHAR2.
        @497  BLANK8   $CHAR30.
        @527  HRSWKJB1 $CHAR2.
        @529  WORKJOB  $CHAR2.
        @531  HRSWKJB2 $CHAR2.
        @533  STPJBHEA $CHAR2.
        @535  MOMALIVE $CHAR2.
        @537  MOMAGED  $CHAR3.
        @540  DADALIVE $CHAR2.
        @542  DADAGED  $CHAR3.
        @545  GENERAL  $CHAR2.
        @547  PRXMHQD  $CHAR2.
        @549  JOINTS   $CHAR2.
        @551  DREVRTEL $CHAR2.
        @553  FRSTARTH $CHAR2.
        @555  ARTHFLG1 $CHAR2.
        @557  DRARTHR  $CHAR2.
        @559  OSTEOART $CHAR2.
        @561  RHEUMATD $CHAR2.
        @563  OTHRTYPE $CHAR2.
        @565  BLANK9   $CHAR30.
        @595  XRYJOINT $CHAR2.
        @597  FRSTXRAY $CHAR2.
        @599  LASTXRAY $CHAR2.
        @601  GOUT     $CHAR2.
        @603  SINCGOUT $CHAR2.
        @605  FRSTGOUT $CHAR2.
        @607  GOUTFLG1 $CHAR2.
        @609  MEMGOUT1 $CHAR2.
        @611  LASTGOUT $CHAR2.
        @613  MEMGOUT2 $CHAR2.
        @615  ARTHGOUT $CHAR2.
        @617  B17_HOSP $CHAR2.
        @619  HEARTATK $CHAR2.
        @621  EVERATT  $CHAR2.
        @623  FIRSTATT $CHAR2.
        @625  ATTFLAG  $CHAR2.
        @627  SINCEART $CHAR2.
        @629  ATTKYR1  $CHAR2.
        @631  ATTKYR2  $CHAR2.
        @633  ATTKYR3  $CHAR2.
        @635  ATTKYR4  $CHAR2.
        @637  ATTFL2_1 $CHAR2.
        @639  ATTFL2_2 $CHAR2.
        @641  ATTFL2_3 $CHAR2.
        @643  ATTFL2_4 $CHAR2.
        @645  B23_HOSP $CHAR2.
        @647  B24_HOSP $CHAR2.
        @649  ADDBYPAS $CHAR2.
        @651  CORONBYP $CHAR2.
        @653  B27_BYPS $CHAR2.
        @655  PACEMAKR $CHAR2.
        @657  B29_PACE $CHAR2.
        @659  ADDSTRKE $CHAR2.
        @661  CVA      $CHAR2.
        @663  STRKYR1  $CHAR2.
        @665  STRKFLAG $CHAR2.
        @667  ADDISTRK $CHAR2.
        @669  STYR2_1  $CHAR2.
        @671  STYR2_2  $CHAR2.
        @673  STFL2_1  $CHAR2.
        @675  STFL2_2  $CHAR2.
        @677  B35_HOSP $CHAR2.
        @679  STRARMLG $CHAR2.
        @681  STRWALK  $CHAR2.
        @683  STRTALK  $CHAR2.
        @685  STRTRBLE $CHAR2.
        @687  BLANK10  $CHAR30.
        @717  CHECK1   $CHAR2.
        @719  DIABMED  $CHAR2.
        @721  SUGRDIAB $CHAR2.
        @723  DIABYR1  $CHAR2.
        @725  DIABFLAG $CHAR2.
        @727  INSLNDB  $CHAR2.
        @729  ORALDB   $CHAR2.
        @731  B42_HOSP $CHAR2.
        @733  HIGHBLCH $CHAR2.
        @735  BLCHMED  $CHAR2.
        @737  BLCHWIGT $CHAR2.
        @739  BLCHFTFD $CHAR2.
        @741  BLCHCHFD $CHAR2.
        @743  BLCHEXER $CHAR2.
        @745  CHMEDLW  $CHAR2.
        @747  CHWIGTLW $CHAR2.
        @749  CHFTFDLW $CHAR2.
        @751  CHCHFDLW $CHAR2.
        @753  CHEXERLW $CHAR2.
        @755  HBPMEDIC $CHAR2.
        @757  HYPER    $CHAR2.
        @759  HBPYEAR1 $CHAR2.
        @761  HIBPFLAG $CHAR2.
        @763  PRESCMED $CHAR2.
        @765  MEDREGLR $CHAR2.
        @767  HGBLWIGT $CHAR2.
        @769  HGBLSALT $CHAR2.
        @771  HGBLEXER $CHAR2.
        @773  HBWIGTLW $CHAR2.
        @775  HBSALTLW $CHAR2.
        @777  HBEXERLW $CHAR2.
        @779  B48_HIGH $CHAR2.
        @781  BRCANYR  $CHAR2.
        @783  CANCTYPE $CHAR2.
        @785  CANCRSRT $CHAR2.
        @787  B52_CANC $CHAR2.
        @789  CANCCNT  $CHAR2.
        @791  CHECK2   $CHAR2.
        @793  FRACHIP  $CHAR2.
        @795  BRKNHIP  $CHAR2.
        @797  HIPYEAR1 $CHAR2.
        @799  HIPFLAG  $CHAR2.
        @801  ANTHRHIP $CHAR2.
        @803  HIPYR2_1 $CHAR2.
        @805  HIPYR2_2 $CHAR2.
        @807  HIPYR2_3 $CHAR2.
        @809  HIPYR2_4 $CHAR2.
        @811  HYRFL2_1 $CHAR2.
        @813  HYRFL2_2 $CHAR2.
        @815  HYRFL2_3 $CHAR2.
        @817  HYRFL2_4 $CHAR2.
        @819  B61_HOSP $CHAR2.
        @821  OSTEOPOR $CHAR2.
        @823  OSTEOYR  $CHAR2.
        @825  ADBKWRST $CHAR2.
        @827  BRKNWRST $CHAR2.
        @829  WRSTYR1  $CHAR2.
        @831  WRSTYR2  $CHAR2.
        @833  WRSTYR3  $CHAR2.
        @835  WRSTYR4  $CHAR2.
        @837  FALLS    $CHAR2.
        @839  NUMFALLS $CHAR2.
        @841  FALLBKBN $CHAR2.
        @843  FALLHEAD $CHAR2.
        @845  FALLMEDC $CHAR2.
        @847  B70_FALL $CHAR2.
        @849  B71_FLU  $CHAR2.
        @851  KIDNYST  $CHAR2.
        @853  EVERKDNY $CHAR2.
        @855  YRTELKID $CHAR2.
        @857  KIDNEYFG $CHAR2.
        @859  DOCKID   $CHAR2.
        @861  FRSTOLDK $CHAR2.
        @863  B74_HOSP $CHAR2.
        @865  SURGCATR $CHAR2.
        @867  EVERCATR $CHAR2.
        @869  CATRSURG $CHAR2.
        @871  YRCATR1  $CHAR2.
        @873  YRCATR2  $CHAR2.
        @875  CATFLAG1 $CHAR2.
        @877  CATFLAG2 $CHAR2.
        @879  B79_HOSP $CHAR2.
        @881  VASECTMY $CHAR2.
        @883  AGEVASEC $CHAR2.
        @885  B83_HOSP $CHAR2.
        @887  FACIL    $CHAR2.
        @889  RESTCNT  $CHAR2.
        @891  HEALTH   $CHAR2.
        @893  PREVMNHT $CHAR2.
        @895  PREVYRHT $CHAR2.
        @897  SUBDIEHN $CHAR2.
        @899  DTHCAUSE $CHAR3.
        @902  SUBJCOND $CHAR2.
        @904  STAYBED  $CHAR2.
        @906  GRLNGTHB $CHAR4.
        @906  LNGTHBED $CHAR2.
        @908  C2UNIT   $CHAR2.
        @910  USELIMBS $CHAR2.
        @912  PARALMB  $CHAR2.
        @914  AMPUTLMB $CHAR2.
        @916  ARTHLMB  $CHAR2.
        @918  OTHLMB   $CHAR2.
        @920  LIMBOTH1 $CHAR2.
        @922  BLANK11  $CHAR25.
        @947  PARARUL  $CHAR2.
        @949  PARALUL  $CHAR2.
        @951  PARARLL  $CHAR2.
        @953  PARALLL  $CHAR2.
        @955  AMPUTRUL $CHAR2.
        @957  AMPUTLUL $CHAR2.
        @959  AMPUTRLL $CHAR2.
        @961  AMPUTLLL $CHAR2.
        @963  OTLMBRUL $CHAR2.
        @965  OTLMBLUL $CHAR2.
        @967  OTLMBRLL $CHAR2.
        @969  OTLMBLLL $CHAR2.
        @971  LIM_CONT $CHAR2.
        @973  USEEQUIP $CHAR2.
        @975  SPBATH   $CHAR2.
        @977  CANE     $CHAR2.
        @979  ARTLIMBS $CHAR2.
        @981  WALKER   $CHAR2.
        @983  WHEELCHR $CHAR2.
        @985  DEVICES  $CHAR2.
        @987  SPCHAIR  $CHAR2.
        @989  EATDEV   $CHAR2.
        @991  CFREQ    $CHAR2.
        @993  C10A     $CHAR2.
        @995  C10B     $CHAR2.
        @997  C10C     $CHAR2.
        @999  C10D     $CHAR2.
        @1001 C10E     $CHAR2.
        @1003 C11A     $CHAR2.
        @1005 C11B     $CHAR2.
        @1007 C11C     $CHAR2.
        @1009 C11D     $CHAR2.
        @1011 C11E     $CHAR2.
        @1013 C12A     $CHAR2.
        @1015 C12B     $CHAR2.
        @1017 C12C     $CHAR2.
        @1019 C12D     $CHAR2.
        @1021 C12E     $CHAR2.
        @1023 C13A     $CHAR2.
        @1025 C13B     $CHAR2.
        @1027 C13C     $CHAR2.
        @1029 C14A     $CHAR2.
        @1031 C14B     $CHAR2.
        @1033 C14C     $CHAR2.
        @1035 C15A     $CHAR2.
        @1037 C15B     $CHAR2.
        @1039 C15C     $CHAR2.
        @1041 C16A     $CHAR2.
        @1043 C16B     $CHAR2.
        @1045 C16C     $CHAR2.
        @1047 C17A     $CHAR2.
        @1049 C17B     $CHAR2.
        @1051 C17C     $CHAR2.
        @1053 C17D     $CHAR2.
        @1055 C17E     $CHAR2.
        @1057 C18A     $CHAR2.
        @1059 C18B     $CHAR2.
        @1061 C18C     $CHAR2.
        @1063 C18D     $CHAR2.
        @1065 C18E     $CHAR2.
        @1067 C19A     $CHAR2.
        @1069 C19B     $CHAR2.
        @1071 C19C     $CHAR2.
        @1073 C19D     $CHAR2.
        @1075 C19E     $CHAR2.
        @1077 C20A     $CHAR2.
        @1079 C20B     $CHAR2.
        @1081 C20C     $CHAR2.
        @1083 C20D     $CHAR2.
        @1085 C20E     $CHAR2.
        @1087 C21A     $CHAR2.
        @1089 C21B     $CHAR2.
        @1091 C21C     $CHAR2.
        @1093 C22A     $CHAR2.
        @1095 C22B     $CHAR2.
        @1097 C22C     $CHAR2.
        @1099 C22D     $CHAR2.
        @1101 C22E     $CHAR2.
        @1103 C23A     $CHAR2.
        @1105 C23B     $CHAR2.
        @1107 C23C     $CHAR2.
        @1109 C24A     $CHAR2.
        @1111 C24B     $CHAR2.
        @1113 C24C     $CHAR2.
        @1115 C24D     $CHAR2.
        @1117 C24E     $CHAR2.
        @1119 C25A     $CHAR2.
        @1121 C25B     $CHAR2.
        @1123 C25C     $CHAR2.
        @1125 C25D     $CHAR2.
        @1127 C25E     $CHAR2.
        @1129 C26A     $CHAR2.
        @1131 C26B     $CHAR2.
        @1133 C26C     $CHAR2.
        @1135 C26D     $CHAR2.
        @1137 C26E     $CHAR2.
        @1139 C27A     $CHAR2.
        @1141 C27B     $CHAR2.
        @1143 C27C     $CHAR2.
        @1145 C28A     $CHAR2.
        @1147 C28B     $CHAR2.
        @1149 C28C     $CHAR2.
        @1151 C28D     $CHAR2.
        @1153 C28E     $CHAR2.
        @1155 C29A     $CHAR2.
        @1157 C29B     $CHAR2.
        @1159 C29C     $CHAR2.
        @1161 C30A     $CHAR2.
        @1163 C30B     $CHAR2.
        @1165 C30C     $CHAR2.
        @1167 C31A     $CHAR2.
        @1169 C31B     $CHAR2.
        @1171 C31C     $CHAR2.
        @1173 C32A     $CHAR2.
        @1175 C32B     $CHAR2.
        @1177 C32C     $CHAR2.
        @1179 RESPC    $CHAR2.
        @1181 BLANK12  $CHAR42.
        @1223 PRXSMDRD $CHAR2.
        @1225 SMOKE100 $CHAR2.
        @1227 SMOKENOW $CHAR2.
        @1229 SMKPERDY $CHAR3.
        @1232 YRSSMOKE $CHAR2.
        @1234 GRMONTHS $CHAR4.
        @1234 MONTHSTP $CHAR2.
        @1236 YEARSTOP $CHAR2.
        @1238 NUMBSMOK $CHAR3.
        @1241 DIDSMOKE $CHAR2.
        @1243 CSMKNOW  $CHAR2.
        @1245 CSMKPRDY $CHAR3.
        @1248 GRNCSMKM $CHAR4.
        @1248 NCSMKMO  $CHAR2.
        @1250 NCSMKYR  $CHAR2.
        @1252 DRINKYR  $CHAR2.
        @1254 GROFTNBE $CHAR7.
        @1254 OFTNBEER $CHAR2.
        @1256 WKMOBEER $CHAR2.
        @1258 NUMBBEER $CHAR3.
        @1261 GROFTNWI $CHAR7.
        @1261 OFTNWINE $CHAR2.
        @1263 WKMOWINE $CHAR2.
        @1265 NUMBWINE $CHAR3.
        @1268 GROFTNLI $CHAR7.
        @1268 OFTNLIQ  $CHAR2.
        @1270 WKMOLIQ  $CHAR2.
        @1272 NUMBSHOT $CHAR3.
        @1275 EXERPROG $CHAR2.
        @1277 GRE2NUM  $CHAR4.
        @1277 E2NUM    $CHAR2.
        @1279 E2UNIT   $CHAR2.
        @1281 GRE3NUM  $CHAR4.
        @1281 E3NUM    $CHAR2.
        @1283 E3UNIT   $CHAR2.
        @1285 SPORTTIM $CHAR2.
        @1287 GRE5NUM  $CHAR4.
        @1287 E5NUM    $CHAR2.
        @1289 E5UNIT   $CHAR2.
        @1291 ACTVTIM  $CHAR2.
        @1293 WHTCOMPR $CHAR2.
        @1295 WEIGHNOW $CHAR3.
        @1298 GRSDIMEN $CHAR13.
        @1298 SDIMENSN $CHAR2.
        @1300 SHEIGHT  $CHAR2.
        @1302 SWGHT25  $CHAR3.
        @1305 SWGHT40  $CHAR3.
        @1308 SWGHT65  $CHAR3.
        @1311 WREYEGLS $CHAR2.
        @1313 SEESTR   $CHAR2.
        @1315 SEEPRINT $CHAR2.
        @1317 HEARAID  $CHAR2.
        @1319 HEARNORM $CHAR2.
        @1321 WOHRGAID $CHAR2.
        @1323 PRXPGMD  $CHAR2.
        @1325 EVERPREG $CHAR2.
        @1327 PREGNOW1 $CHAR2.
        @1329 FRSTBRTH $CHAR2.
        @1331 SINCPREG $CHAR2.
        @1333 PREGNOW2 $CHAR2.
        @1335 LASTBRTH $CHAR2.
        @1337 LIVEBRTH $CHAR2.
        @1339 MISCARAG $CHAR2.
        @1341 NUMMISS  $CHAR2.
        @1343 HAVEWOMB $CHAR2.
        @1345 AGEREMVD $CHAR2.
        @1347 BOTHOVRY $CHAR2.
        @1349 ONEOVRY  $CHAR2.
        @1351 REMVOVRY $CHAR2.
        @1353 HAVPERD  $CHAR2.
        @1355 AGEPERD  $CHAR2.
        @1357 PERDREG  $CHAR2.
        @1359 CHNGLIFE $CHAR2.
        @1361 HORMONE  $CHAR2.
        @1363 AGEHPILL $CHAR2.
        @1365 GRG20UNI $CHAR9.
        @1365 G20UNITA $CHAR2.
        @1367 HPIL1MOL $CHAR2.
        @1369 HPIL1YRL $CHAR2.
        @1371 G20ATOT  $CHAR3.
        @1374 GRG20    $CHAR9.
        @1374 G20UNITB $CHAR2.
        @1376 HPIL1MOT $CHAR2.
        @1378 HPIL1YRT $CHAR2.
        @1380 G20BTOT  $CHAR3.
        @1383 PILLCHNG $CHAR2.
        @1385 GRG22UNI $CHAR9.
        @1385 G22UNITA $CHAR2.
        @1387 HPIL2MOL $CHAR2.
        @1389 HPIL2YRL $CHAR2.
        @1391 G22ATOT  $CHAR3.
        @1394 GRG22UNB $CHAR9.
        @1394 G22UNITB $CHAR2.
        @1396 HPIL2MOT $CHAR2.
        @1398 HPIL2YRT $CHAR2.
        @1400 G22BTOT  $CHAR3.
        @1403 CURTAKHM $CHAR2.
        @1405 COLORPIL $CHAR2.
        @1407 GRUNIT25 $CHAR4.
        @1407 UNIT25   $CHAR2.
        @1409 LONGCOLR $CHAR2.
        @1411 PROVERA  $CHAR2.
        @1413 CURPROV  $CHAR2.
        @1415 GRUNIT28 $CHAR4.
        @1415 UNIT28   $CHAR2.
        @1417 LONGPIL2 $CHAR2.
        @1419 BRTHPILL $CHAR2.
        @1421 AGELASTP $CHAR2.
        @1423 GRG31UNI $CHAR9.
        @1423 G31UNITA $CHAR2.
        @1425 BPIL1MOL $CHAR2.
        @1427 BPIL1YRL $CHAR2.
        @1429 G31ATOT  $CHAR3.
        @1432 GRG31UNB $CHAR9.
        @1432 G31UNITB $CHAR2.
        @1434 BPIL1MOT $CHAR2.
        @1436 BPIL1YRT $CHAR2.
        @1438 G31BTOT  $CHAR3.
        @1441 BRTHPIL2 $CHAR2.
        @1443 AGEFRSTP $CHAR2.
        @1445 CURPILL  $CHAR2.
        @1447 AGELSTP2 $CHAR2.
        @1449 GRG36UNA $CHAR9.
        @1449 G36UNITA $CHAR2.
        @1451 BPIL2MOL $CHAR2.
        @1453 BPIL2YRL $CHAR2.
        @1455 G36ATOT  $CHAR3.
        @1458 GRG36UNB $CHAR9.
        @1458 G36UNITB $CHAR2.
        @1460 BPIL2MOT $CHAR2.
        @1462 BPIL2YRT $CHAR2.
        @1464 G36BTOT  $CHAR3.
        @1467 GRG37UNI $CHAR6.
        @1467 G37UNIT  $CHAR2.
        @1469 BPIL25MO $CHAR2.
        @1471 BPIL25YR $CHAR2.
        @1473 BEFCHILD $CHAR2.
        @1475 GRG39UNI $CHAR6.
        @1475 G39UNIT  $CHAR2.
        @1477 BPILBCMO $CHAR2.
        @1479 BPILBCYR $CHAR2.
        @1481 TUBETYD  $CHAR2.
        @1483 AGETUBTY $CHAR2.
        @1485 CALCIUM  $CHAR2.
        @1487 GRG43UNI $CHAR4.
        @1487 UNIT43   $CHAR2.
        @1489 LONGCALC $CHAR2.
        @1491 PAPTEST  $CHAR2.
        @1493 LONGPAP  $CHAR2.
        @1495 MANYPAP5 $CHAR2.
        @1497 BRSTEXAM $CHAR2.
        @1499 NUMBRST5 $CHAR2.
        @1501 LONGBRST $CHAR2.
        @1503 EXAMSELF $CHAR2.
        @1505 EVEREXAM $CHAR2.
        @1507 OFTNEXAM $CHAR2.
        @1509 MAMMO    $CHAR2.
        @1511 NUMMAMO5 $CHAR2.
        @1513 LASTMAMO $CHAR2.
        @1515 MEDICARE $CHAR2.
        @1517 HHCF     $CHAR2.
        @1519 BLANK13  $CHAR90.
        @1609 RELAPRX1 $CHAR2.
        @1611 BLANK14  $CHAR128.
        @1739 SUBAST   $CHAR2.
        @1741 NUMAST   $CHAR2.
        @1743 AST1REL  $CHAR2.
        @1745 BLANK15  $CHAR184.
        @1929 PRIMAST  $CHAR2.
        @1931 GRKHEAR  $CHAR140.
        @1931 KHEAR    $CHAR2.
        @1933 KSPEECH  $CHAR2.
        @1935 KLANGU   $CHAR2.
        @1937 KMEMRY   $CHAR2.
        @1939 KINSTIT  $CHAR2.
        @1941 KALZH    $CHAR2.
        @1943 KOTHMENT $CHAR2.
        @1945 BLANK16  $CHAR30.
        @1975 KOTHPHY  $CHAR2.
        @1977 BLANK17  $CHAR30.
        @2007 KOTHHEAL $CHAR2.
        @2009 BLANK18  $CHAR30.
        @2039 KOTHER   $CHAR2.
        @2041 BLANK19  $CHAR30.
        @2071 INFOSATS $CHAR2.
        @2073 BLANK20  $CHAR195.
        @2268 SUBAWARE $CHAR2.
        @2270 QHELDATT $CHAR2.
        @2272 QUPSTDEP $CHAR2.
        @2274 QBORING  $CHAR2.
        @2276 RCAPABLE $CHAR2.
        @2278 RACCURTE $CHAR2.
        @2280 RUNDESST $CHAR2.
        @2282 BADSECT  $CHAR2.
        @2284 BLANK21  $CHAR95.
        @2379 RHRDHRNG $CHAR2.
        @2381 QINTSPAN $CHAR2.
        @2383 BLANK22  $CHAR653.
        @3036 GRCANC1  $CHAR300.
        @3036 BLANK23  $CHAR5.
        @3041 CANCNUM1 $CHAR2.
        @3043 CACRLOC1 $CHAR2.
        @3045 BLANK24  $CHAR30.
        @3075 IC9CANC1 $CHAR3.
        @3078 ANYCANC1 $CHAR2.
        @3080 TODCANC1 $CHAR2.
        @3082 CANCFL1  $CHAR2.
        @3084 B5_HOSP1 $CHAR2.
        @3086 BLANK25  $CHAR5.
        @3091 CANCNUM2 $CHAR2.
        @3093 CACRLOC2 $CHAR2.
        @3095 BLANK26  $CHAR30.
        @3125 IC9CANC2 $CHAR3.
        @3128 ANYCANC2 $CHAR2.
        @3130 TODCANC2 $CHAR2.
        @3132 CANCFL2  $CHAR2.
        @3134 B5_HOSP2 $CHAR2.
        @3136 BLANK27  $CHAR5.
        @3141 CANCNUM3 $CHAR2.
        @3143 CACRLOC3 $CHAR2.
        @3145 BLANK28  $CHAR30.
        @3175 IC9CANC3 $CHAR3.
        @3178 ANYCANC3 $CHAR2.
        @3180 TODCANC3 $CHAR2.
        @3182 CANCFL3  $CHAR2.
        @3184 B5_HOSP3 $CHAR2.
        @3186 BLANK29  $CHAR5.
        @3191 CANCNUM4 $CHAR2.
        @3193 CACRLOC4 $CHAR2.
        @3195 BLANK30  $CHAR30.
        @3225 IC9CANC4 $CHAR3.
        @3228 ANYCANC4 $CHAR2.
        @3230 TODCANC4 $CHAR2.
        @3232 CANCFL4  $CHAR2.
        @3234 B5_HOSP4 $CHAR2.
        @3236 BLANK31  $CHAR5.
        @3241 CANCNUM5 $CHAR2.
        @3243 CACRLOC5 $CHAR2.
        @3245 BLANK32  $CHAR30.
        @3275 IC9CANC5 $CHAR3.
        @3278 ANYCANC5 $CHAR2.
        @3280 TODCANC5 $CHAR2.
        @3282 CANCFL5  $CHAR2.
        @3284 B5_HOSP5 $CHAR2.
        @3286 BLANK33  $CHAR5.
        @3291 CANCNUM6 $CHAR2.
        @3293 CACRLOC6 $CHAR2.
        @3295 BLANK34  $CHAR30.
        @3325 IC9CANC6 $CHAR3.
        @3328 ANYCANC6 $CHAR2.
        @3330 TODCANC6 $CHAR2.
        @3332 CANCFL6  $CHAR2.
        @3334 B5_HOSP6 $CHAR2.
        @3336 BLANK35  $CHAR5.
        @3341 RESTNUM1 $CHAR2.
        @3343 ADSNPLC1 $CHAR2.
        @3345 BLANK36  $CHAR30.
        @3375 ENERFRM1 $CHAR2.
        @3377 BLANK37  $CHAR30.
        @3407 YERENTR1 $CHAR2.
        @3409 NUSCARE1 $CHAR2.
        @3411 SUGRECP1 $CHAR2.
        @3413 NEDHELP1 $CHAR2.
        @3415 RESPCMD1 $CHAR2.
        @3417 COFUSED1 $CHAR2.
        @3419 CNDTNM11 $CHAR2.
        @3421 BLANK38  $CHAR30.
        @3451 CNDTNM21 $CHAR2.
        @3453 BLANK39  $CHAR30.
        @3483 CNDTNM31 $CHAR2.
        @3485 BLANK40  $CHAR30.
        @3515 CNDTNM41 $CHAR2.
        @3517 BLANK41  $CHAR30.
        @3547 CNDTNM51 $CHAR2.
        @3549 BLANK42  $CHAR30.
        @3579 RECODE11 $CHAR2.
        @3581 RECODE21 $CHAR2.
        @3583 RECODE31 $CHAR2.
        @3585 RECODE41 $CHAR2.
        @3587 RECODE51 $CHAR2.
        @3589 RECODE61 $CHAR2.
        @3591 RECODE71 $CHAR2.
        @3593 RECODE81 $CHAR2.
        @3595 RECODE91 $CHAR2.
        @3597 REODE101 $CHAR2.
        @3599 REODE111 $CHAR2.
        @3601 REODE121 $CHAR2.
        @3603 REODE131 $CHAR2.
        @3605 REODE141 $CHAR2.
        @3607 REODE151 $CHAR2.
        @3609 REODE161 $CHAR2.
        @3611 REODE171 $CHAR2.
        @3613 REODE181 $CHAR2.
        @3615 REODE191 $CHAR2.
        @3617 B92NUM1  $CHAR2.
        @3619 B92UNIT1 $CHAR2.
        @3621 OTADMSN1 $CHAR2.
        @3623 BLANK43  $CHAR7.
        @3630 RESTNUM2 $CHAR2.
        @3632 ADSNPLC2 $CHAR2.
        @3634 BLANK44  $CHAR30.
        @3664 ENERFRM2 $CHAR2.
        @3666 BLANK45  $CHAR30.
        @3696 YERENTR2 $CHAR2.
        @3698 NUSCARE2 $CHAR2.
        @3700 SUGRECP2 $CHAR2.
        @3702 NEDHELP2 $CHAR2.
        @3704 RESPCMD2 $CHAR2.
        @3706 COFUSED2 $CHAR2.
        @3708 CNDTNM12 $CHAR2.
        @3710 BLANK46  $CHAR30.
        @3740 CNDTNM22 $CHAR2.
        @3742 BLANK47  $CHAR30.
        @3772 CNDTNM32 $CHAR2.
        @3774 BLANK48  $CHAR30.
        @3804 CNDTNM42 $CHAR2.
        @3806 BLANK49  $CHAR30.
        @3836 CNDTNM52 $CHAR2.
        @3838 BLANK50  $CHAR30.
        @3868 RECODE12 $CHAR2.
        @3870 RECODE22 $CHAR2.
        @3872 RECODE32 $CHAR2.
        @3874 RECODE42 $CHAR2.
        @3876 RECODE52 $CHAR2.
        @3878 RECODE62 $CHAR2.
        @3880 RECODE72 $CHAR2.
        @3882 RECODE82 $CHAR2.
        @3884 RECODE92 $CHAR2.
        @3886 REODE102 $CHAR2.
        @3888 REODE112 $CHAR2.
        @3890 REODE122 $CHAR2.
        @3892 REODE132 $CHAR2.
        @3894 REODE142 $CHAR2.
        @3896 REODE152 $CHAR2.
        @3898 REODE162 $CHAR2.
        @3900 REODE172 $CHAR2.
        @3902 REODE182 $CHAR2.
        @3904 REODE192 $CHAR2.
        @3906 B92NUM2  $CHAR2.
        @3908 B92UNIT2 $CHAR2.
        @3910 OTADMSN2 $CHAR2.
        @3912 SAMEREA2 $CHAR2.
        @3914 BLANK51  $CHAR5.
        @3919 RESTNUM3 $CHAR2.
        @3921 ADSNPLC3 $CHAR2.
        @3923 BLANK52  $CHAR30.
        @3953 ENERFRM3 $CHAR2.
        @3955 BLANK53  $CHAR30.
        @3985 YERENTR3 $CHAR2.
        @3987 NUSCARE3 $CHAR2.
        @3989 SUGRECP3 $CHAR2.
        @3991 NEDHELP3 $CHAR2.
        @3993 RESPCMD3 $CHAR2.
        @3995 COFUSED3 $CHAR2.
        @3997 CNDTNM13 $CHAR2.
        @3999 BLANK54  $CHAR30.
        @4029 CNDTNM23 $CHAR2.
        @4031 BLANK55  $CHAR30.
        @4061 CNDTNM33 $CHAR2.
        @4063 BLANK56  $CHAR30.
        @4093 CNDTNM43 $CHAR2.
        @4095 BLANK57  $CHAR30.
        @4125 CNDTNM53 $CHAR2.
        @4127 BLANK58  $CHAR30.
        @4157 RECODE13 $CHAR2.
        @4159 RECODE23 $CHAR2.
        @4161 RECODE33 $CHAR2.
        @4163 RECODE43 $CHAR2.
        @4165 RECODE53 $CHAR2.
        @4167 RECODE63 $CHAR2.
        @4169 RECODE73 $CHAR2.
        @4171 RECODE83 $CHAR2.
        @4173 RECODE93 $CHAR2.
        @4175 REODE103 $CHAR2.
        @4177 REODE113 $CHAR2.
        @4179 REODE123 $CHAR2.
        @4181 REODE133 $CHAR2.
        @4183 REODE143 $CHAR2.
        @4185 REODE153 $CHAR2.
        @4187 REODE163 $CHAR2.
        @4189 REODE173 $CHAR2.
        @4191 REODE183 $CHAR2.
        @4193 REODE193 $CHAR2.
        @4195 B92NUM3  $CHAR2.
        @4197 B92UNIT3 $CHAR2.
        @4199 OTADMSN3 $CHAR2.
        @4201 BLANK59  $CHAR7.
        @4208 RESTNUM4 $CHAR2.
        @4210 ADSNPLC4 $CHAR2.
        @4212 BLANK60  $CHAR30.
        @4242 ENERFRM4 $CHAR2.
        @4244 BLANK61  $CHAR30.
        @4274 YERENTR4 $CHAR2.
        @4276 NUSCARE4 $CHAR2.
        @4278 SUGRECP4 $CHAR2.
        @4280 NEDHELP4 $CHAR2.
        @4282 RESPCMD4 $CHAR2.
        @4284 COFUSED4 $CHAR2.
        @4286 CNDTNM14 $CHAR2.
        @4288 BLANK62  $CHAR30.
        @4318 CNDTNM24 $CHAR2.
        @4320 BLANK63  $CHAR30.
        @4350 CNDTNM34 $CHAR2.
        @4352 BLANK64  $CHAR30.
        @4382 CNDTNM44 $CHAR2.
        @4384 BLANK65  $CHAR30.
        @4414 CNDTNM54 $CHAR2.
        @4416 BLANK66  $CHAR30.
        @4446 RECODE14 $CHAR2.
        @4448 RECODE24 $CHAR2.
        @4450 RECODE34 $CHAR2.
        @4452 RECODE44 $CHAR2.
        @4454 RECODE54 $CHAR2.
        @4456 RECODE64 $CHAR2.
        @4458 RECODE74 $CHAR2.
        @4460 RECODE84 $CHAR2.
        @4462 RECODE94 $CHAR2.
        @4464 REODE104 $CHAR2.
        @4466 REODE114 $CHAR2.
        @4468 REODE124 $CHAR2.
        @4470 REODE134 $CHAR2.
        @4472 REODE144 $CHAR2.
        @4474 REODE154 $CHAR2.
        @4476 REODE164 $CHAR2.
        @4478 REODE174 $CHAR2.
        @4480 REODE184 $CHAR2.
        @4482 REODE194 $CHAR2.
        @4484 B92NUM4  $CHAR2.
        @4486 B92UNIT4 $CHAR2.
        @4488 OTADMSN4 $CHAR2.
        @4490 BLANK67  $CHAR7.
        @4497 RESTNUM5 $CHAR2.
        @4499 ADSNPLC5 $CHAR2.
        @4501 BLANK68  $CHAR30.
        @4531 ENERFRM5 $CHAR2.
        @4533 BLANK69  $CHAR30.
        @4563 YERENTR5 $CHAR2.
        @4565 NUSCARE5 $CHAR2.
        @4567 SUGRECP5 $CHAR2.
        @4569 NEDHELP5 $CHAR2.
        @4571 RESPCMD5 $CHAR2.
        @4573 COFUSED5 $CHAR2.
        @4575 CNDTNM15 $CHAR2.
        @4577 BLANK70  $CHAR30.
        @4607 CNDTNM25 $CHAR2.
        @4609 BLANK71  $CHAR30.
        @4639 CNDTNM35 $CHAR2.
        @4641 BLANK72  $CHAR30.
        @4671 CNDTNM45 $CHAR2.
        @4673 BLANK73  $CHAR30.
        @4703 CNDTNM55 $CHAR2.
        @4705 BLANK74  $CHAR30.
        @4735 RECODE15 $CHAR2.
        @4737 RECODE25 $CHAR2.
        @4739 RECODE35 $CHAR2.
        @4741 RECODE45 $CHAR2.
        @4743 RECODE55 $CHAR2.
        @4745 RECODE65 $CHAR2.
        @4747 RECODE75 $CHAR2.
        @4749 RECODE85 $CHAR2.
        @4751 RECODE95 $CHAR2.
        @4753 REODE105 $CHAR2.
        @4755 REODE115 $CHAR2.
        @4757 REODE125 $CHAR2.
        @4759 REODE135 $CHAR2.
        @4761 REODE145 $CHAR2.
        @4763 REODE155 $CHAR2.
        @4765 REODE165 $CHAR2.
        @4767 REODE175 $CHAR2.
        @4769 REODE185 $CHAR2.
        @4771 REODE195 $CHAR2.
        @4773 B92NUM5  $CHAR2.
        @4775 B92UNIT5 $CHAR2.
        @4777 OTADMSN5 $CHAR2.
        @4779 BLANK75  $CHAR7.
        @4786 RESTNUM6 $CHAR2.
        @4788 ADSNPLC6 $CHAR2.
        @4790 BLANK76  $CHAR30.
        @4820 ENERFRM6 $CHAR2.
        @4822 BLANK77  $CHAR30.
        @4852 YERENTR6 $CHAR2.
        @4854 NUSCARE6 $CHAR2.
        @4856 SUGRECP6 $CHAR2.
        @4858 NEDHELP6 $CHAR2.
        @4860 RESPCMD6 $CHAR2.
        @4862 COFUSED6 $CHAR2.
        @4864 CNDTNM16 $CHAR2.
        @4866 BLANK78  $CHAR30.
        @4896 CNDTNM26 $CHAR2.
        @4898 BLANK79  $CHAR30.
        @4928 CNDTNM36 $CHAR2.
        @4930 BLANK80  $CHAR30.
        @4960 CNDTNM46 $CHAR2.
        @4962 BLANK81  $CHAR30.
        @4992 CNDTNM56 $CHAR2.
        @4994 BLANK82  $CHAR30.
        @5024 RECODE16 $CHAR2.
        @5026 RECODE26 $CHAR2.
        @5028 RECODE36 $CHAR2.
        @5030 RECODE46 $CHAR2.
        @5032 RECODE56 $CHAR2.
        @5034 RECODE66 $CHAR2.
        @5036 RECODE76 $CHAR2.
        @5038 RECODE86 $CHAR2.
        @5040 RECODE96 $CHAR2.
        @5042 REODE106 $CHAR2.
        @5044 REODE116 $CHAR2.
        @5046 REODE126 $CHAR2.
        @5048 REODE136 $CHAR2.
        @5050 REODE146 $CHAR2.
        @5052 REODE156 $CHAR2.
        @5054 REODE166 $CHAR2.
        @5056 REODE176 $CHAR2.
        @5058 REODE186 $CHAR2.
        @5060 REODE196 $CHAR2.
        @5062 B92NUM6  $CHAR2.
        @5064 B92UNIT6 $CHAR2.
        @5066 OTADMSN6 $CHAR2.
        @5068 BLANK83  $CHAR2.
        @5070 HCFSR01  $CHAR2.
        @5072 HCFSR02  $CHAR2.
        @5074 HCFSR03  $CHAR2.
        @5076 HCFSR04  $CHAR2.
        @5078 HCFSR05  $CHAR2.
        @5080 HCFSR06  $CHAR2.
        @5082 BLANK84  $CHAR2.
        @5084 HCFSR08  $CHAR2.
        @5086 HCFSR09  $CHAR2.
        @5088 HCFSR10  $CHAR2.
        @5090 HCFSR11  $CHAR2.
        @5092 HCFSR12  $CHAR2.
        @5094 HCFSR13  $CHAR2.
        @5096 BLANK85  $CHAR2.
        @5098 HCFSR15  $CHAR2.
        @5100 HCFSR16  $CHAR2.
        @5102 HCFSR17  $CHAR2.
        @5104 HCFSR18  $CHAR2.
        @5106 HCFSR19  $CHAR2.
        @5108 HCFSR20  $CHAR2.
        @5110 HCFSR21  $CHAR2.
        @5112 HCFSR22  $CHAR2.
        @5114 HCFSR23  $CHAR2.
        @5116 HCFSR24  $CHAR2.
        @5118 HCFSR25  $CHAR2.
        @5120 HCFSR26  $CHAR2.
        @5122 HCFSR27  $CHAR2.
        @5124 HCFSR28  $CHAR2.
        @5126 HCFSR29  $CHAR2.
        @5128 HCFSR30  $CHAR2.
        @5130 HCFSR31  $CHAR2.
        @5132 HCFSR32  $CHAR2.
        @5134 HCFSR33  $CHAR2.
        @5136 HCFSR34  $CHAR2.
        @5138 HCFSR35  $CHAR2.
        @5140 HCFSR36  $CHAR2.
        @5142 HCFSR37  $CHAR2.
        @5144 CAUSEDTH $CHAR4.
        @5148 STRATUM  $CHAR2.
        @5150 PSU      $CHAR3.
        @5153 SUBSAMPL $CHAR2.
        @5155 SWGT1    $CHAR6.
        @5161 SWGT2    $CHAR6.
        @5167 SWGT3    $CHAR6.
        @5173 SWGT4    $CHAR6.
        @5179 SWGT5    $CHAR6.
        @5185 SWGT6    $CHAR6.
        ;
*** THIS NEXT STATEMENT ASSIGNS LABELS *** ;                                                                                
LABEL SEQNO    = 'SAMPLE SEQUENCE NUMBER'
      PREVINT  = 'WAS SUBJECT PREVIOUSLY INTERVIEWED'
      SUBSEX   = 'SEX OF SUBJECT'
      TRACSTAT = 'SUBJECT VITAL STATUS'
      GRRSLTMO = 'DATE OF INTERVIEW1987 FOLLOWUP'
      RSLTMO   = 'MONTH'
      RSLTDAY  = 'DAY OF INTERVIEW'
      RSLTYR   = 'YEAR'
      AGENOW   = 'AGE OF SUBJECT AS OF DEC 31, 1986'
      BASERSLT = 'MOST CURRENT RESULT CODE'
      DCRECD   = 'DEATH CERTIFICATE RECEIVED'
      GRDEATHM = 'DATE OF DEATH1987 FOLLOWUP'
      DEATHMO  = 'MONTH'
      DEATHDAY = 'DAY'
      DEATHYR  = 'YEAR'
      ARTHECF  = 'S REPORTED ARTHRITIS ON ECF'
      GOUTECF  = 'S REPORTED GOUT ON ECF'
      HEARTATT = 'S REPORTED HEART ATTACK ON IF/ECF'
      HEARTOTH = 'S REPORTED OTH HEART CONDITION ON IF/ECF'
      BYPASECF = 'S REPORTED CORON BYPASS ON ECF'
      PACEECF  = 'S REPORTED PACEMKR ON ECF'
      STROKE   = 'S REPORTED STROKE ON IF/ECF'
      DIABETES = 'S REPORTED DIABETES ON IF/ECF'
      BLOODPRE = 'S REPORTED HIGH BLOOD PRES ON IF/ECF'
      BPMEDECF = 'S REPORTED HBP MED ON ECF'
      BROKENHI = 'S REPORTED BROKEN HIP ON IF/ECF'
      CANCER   = 'S REPORTED CANCER ON IF/ECF'
      BRCANCER = 'S REPORTED BREAST CANCER ON IF'
      KIDNEYIF = 'S REPORTED KIDNEY DIS OR STNS ON IF'
      CATARECF = 'S REPORTED CATARACT SURGERY ON ECF'
      LIVARECF = 'S REPORTED NH ON ECF'
      WORKIF   = 'S REPORTED WORKING ON IF'
      RETIREIF = 'S REPORTED RETIRED, KEEP HOUSE ON IF'
      MOMALIF  = 'S REPORTED MOTHER ALIVE ON IF'
      DADALIF  = 'S REPORTED FATHER ALIVE ON IF'
      SMOKSTAT = 'S SMOKES NOW, FORMERLY, NEVER ON IF/ECF'
      LIVBRTH1 = 'S REPORTED LIVE BIRTH ON IF'
      PREGIF   = 'S REPORTED PREG ON IF'
      UTERUSIF = 'S REPORTED INTACT UTERUS ON IF OR DK'
      OVARYIF  = 'S HAD ONE, BOTH OR NO OVARIES ON IF'
      PERIODIF = 'S REPORTED HAVING PERIODS ON IF'
      HORMONES = 'S REPORTED TAKING HORMONE PILL ON IF/ECF'
      BCPILLIF = 'S REPORTED TAKING BC PILLS ON IF'
      BCPILL25 = 'S TOOK BCPILLS BFR AGE 25 ON IF/ECF'
      GRIDATEM = 'DATE OF INTERVIEW 1982-1984 FOLLOWUP'
      IDATEMM  = 'MONTH'
      IDATEDAY = 'DAY'
      IDATEYR  = 'YEAR'
      GRCFMONT = 'DATE OF INTERVIEW 1986 FOLLOWUP'
      CFMONTH  = 'MONTH'
      CFDAY    = 'DAY'
      CFYEAR   = 'YEAR'
      GREXAMMO = 'DATE OF NHANES I EXAM'
      EXAMMO   = 'MONTH'
      EXAMDAY  = 'DAY'
      EXAMYR   = 'YEAR'
      GRBIRTHM = 'NHEFS DATE OF BIRTH'
      BIRTHMO  = 'MONTH'
      BDATE2   = 'YEAR'
      AGEEXAM  = 'AGE OF SUBJECT AT NHANESI EXAM'
      AGEIF    = 'AGE OF SUBJECT AT INITIAL FOLLOWUP'
      AGECF    = 'AGE OF SUBJECT AT ECF'
      AGECONT  = 'AGE AT LAST INTERVIEW IF/ECF'
      ELIGECF  = 'ELIGIBLE FOR ECF'
      GRCONTMO = 'DATE OF MOST RECENT INTERVIEW'
      CONTMO   = 'MONTH'
      CONTDAY  = 'DAY'
      CONTYR   = 'YEAR'
      EFVIT    = 'VITAL STATUS 1986 NHEFS'
      QDISIF   = 'QUESTIONNAIRE DISPOSITION AT IF'
      IFVIT    = 'IF VITAL STATUS'
      QDISECF  = 'QUESTIONNAIRE DISPOSITION AT ECF'
      QVERSION = 'TELEPHONE OR MAIL QUESTIONNAIRE'
      REVRACE  = 'REVISED RACE'
      PRELA    = 'PROXY RELATIONSHIP'
      RELATOS  = 'HOW WAS RESPONDENT RELATED TO SUBJECT'
      LIVEARRG = 'S CURRENT LIVING ARRANGEMENT'
      SDIENRHM = 'WAS S IN NH AT TIME OF DEATH'
      PRXLIVWD = 'R LIVED WITH S 1 YR PRIOR TO DEATH'
      PRXVISTD = 'HOW FREQ R VISIT S YR BEFORE DEATH'
      NHCONTU  = 'LIVED IN NH CONTINUOUSLY'
      SAMENH   = 'SAME NH AS ECF'
      NUMSLIVE = "NUMBER OF PEOPLE IN S'S HOUSEHOLD"
      GRLGTHAL = 'HOW LONG HAS SUBJECT LIVED ALONE?'
      LGTHALNE = 'HOW LONG HAD S LIVED ALONE'
      LGTHUNIT = 'TIME PERIOD RESPONDED IN'
      GRRELATO = 'RELATIONSHIP TO S'
      RELTOS1  = '1ST RELATIONSHIP'
      RELTOS2  = '2ND RELATIONSHIP'
      RELTOS3  = '3RD RELATIONSHIP'
      RELTOS4  = '4TH RELATIONSHIP'
      RELTOS5  = '5TH RELATIONSHIP'
      RELTOS6  = '6TH RELATIONSHIP'
      RELTOS7  = '7TH RELATIONSHIP'
      RELTOS8  = '8TH RELATIONSHIP'
      RELTOS9  = '9TH RELATIONSHIP'
      RELTOS10 = '10TH RELATIONSHIP'
      RELTOS11 = '11TH RELATIONSHIP'
      RELTOS12 = '12TH RELATIONSHIP'
      RELTOS13 = '13TH RELATIONSHIP'
      GRRELSEX = 'SEX EA HOUSEHOLD MEM CURRENTLY LIV W/ S'
      RELSEX1  = 'SEX OF 1ST MEMBER'
      RELSEX2  = 'SEX OF 2ND MEMBER'
      RELSEX3  = 'SEX OF 3RD MEMBER'
      RELSEX4  = 'SEX OF 4TH MEMBER'
      RELSEX5  = 'SEX OF 5TH MEMBER'
      RELSEX6  = 'SEX OF 6TH MEMBER'
      RELSEX7  = 'SEX OF 7TH MEMBER'
      RELSEX8  = 'SEX OF 8TH MEMBER'
      RELSEX9  = 'SEX OF 9TH MEMBER'
      RELSEX10 = 'SEX OF 10TH MEMBER'
      RELSEX11 = 'SEX OF 11TH MEMBER'
      RELSEX12 = 'SEX OF 12TH MEMBER'
      RELSEX13 = 'SEX OF 13TH MEMBER'
      NUMSLVED = 'NUMBER OF PEOPLE IN FORMER HOUSEHOLD'
      GRLGTHA2 = 'TIME PERIOD S LIVED ALONE'
      LGTHALN2 = 'NUMBER OF MONTHS/YEARS S LIVED ALONE'
      LGTHUNT2 = 'TIME PERIOD RESPONDED IN'
      GRRELDOS = 'RELATIONSHIP TO S PRIOR TO NURSING HOME'
      RELDOS1  = '1ST RELATIONSHIP'
      RELDOS2  = '2ND RELATIONSHIP'
      RELDOS3  = '3RD RELATIONSHIP'
      RELDOS4  = '4TH RELATIONSHIP'
      RELDOS5  = '5TH RELATIONSHIP'
      RELDOS6  = '6TH RELATIONSHIP'
      RELDOS7  = '7TH RELATIONSHIP'
      RELDOS8  = '8TH RELAITONSHIP'
      RELDOS9  = '9TH RELATIONSHIP'
      RELDOS10 = '10TH RELATIONSHIP'
      RELDOS11 = '11TH RELATIONSHIP'
      RELDOS12 = '12TH RELATIONSHIP'
      GRRELDSX = 'SEX OF M LIVING W/ S PRIOR TO NURSING HM'
      RELDSX1  = 'SEX OF 1ST MEMBER'
      RELDSX2  = 'SEX OF 2ND MEMBER'
      RELDSX3  = 'SEX OF 3RD MEMBER'
      RELDSX4  = 'SEX OF 4TH MEMBER'
      RELDSX5  = 'SEX OF 5TH MEMBER'
      RELDSX6  = 'SEX OF 6TH MEMBER'
      RELDSX7  = 'SEX OF 7TH MEMBER'
      RELDSX8  = 'SEX OF 8TH MEMBER'
      RELDSX9  = 'SEX OF 9TH MEMBER'
      RELDSX10 = 'SEX OF 10TH MEMBER'
      RELDSX11 = 'SEX OF 11TH MEMBER'
      RELDSX12 = 'SEX OF 12TH MEMBER'
      MARRSTAT = 'MARITAL STATUS OF SUBJECT'
      SUBJRACE = 'RACE OF SUBJECT'
      HISPANIC = 'IS S OF HISPANIC ORIGIN'
      DOINGMST = 'WHAT IS S DOING MOST'
      HRSWKJB1 = 'HOURS WORK PER WEEK'
      WORKJOB  = 'WORKED AT ALL LAST 3 MONTHS'
      HRSWKJB2 = 'HOURS WORKED PER WEEK'
      STPJBHEA = 'STOPPED WORKING DUE TO HEALTH'
      MOMALIVE = 'MOTHER LIVING'
      MOMAGED  = 'MOTHER AGE AT DEATH'
      DADALIVE = 'FATHER ALIVE'
      DADAGED  = 'FATHER AGE AT DEATH'
      GENERAL  = 'GENERAL HEALTH OF SUBJECT'
      PRXMHQD  = 'CAN PROXY COMPLETE SECTION B'
      JOINTS   = 'PAIN, SWELLING, STIFF JOINTS'
      DREVRTEL = 'DID S HAVE ARTHRITIS'
      FRSTARTH = 'FIRST TOLD HAD ARTHRITIS'
      ARTHFLG1 = 'ARTHRITIS NOT PREV REP/REP < PREV INT YR'
      DRARTHR  = 'DID DR SAY WHICH TYPE ARTHR S HAD'
      OSTEOART = 'S HAD OSTEO/DEGENERATIVE ARTH'
      RHEUMATD = 'S HAD RHEUMATOID ARTHRITIS'
      OTHRTYPE = 'S HAD SOME OTHER TYPE OF ARTHRITIS'
      XRYJOINT = 'EVER HAD AN X-RAY OF ANY JOINTS'
      FRSTXRAY = 'HOW LONG AGO S FIRST HAD X-RAY'
      LASTXRAY = 'HOW LONG AGO S LAST HAD X-RAY'
      GOUT     = 'DOCTOR CONFIRMED GOUT'
      SINCGOUT = 'ADDITIONAL EPISODE OF GOUT'
      FRSTGOUT = 'WHAT YR WAS S FIRST TOLD ABOUT GOUT'
      GOUTFLG1 = 'GOUT NOT PREV REPORTED, YR < PREV INT YR'
      MEMGOUT1 = 'WAS IT LESS THAN A YEAR AGO'
      LASTGOUT = 'WHAT YR DID S HAVE LAST GOUT EPIS'
      MEMGOUT2 = 'WAS IT LESS THAN A YEAR AGO'
      ARTHGOUT = 'DID DR SAY S HAD ARTHR CAUS BY GOUT'
      B17_HOSP = 'WAS S HOSP FOR GOUT OR ARTHR'
      HEARTATK = 'DID S HAVE ADDITIONAL HEART ATTACK'
      EVERATT  = 'DID DR SAY S HAD A HEART ATTACK'
      FIRSTATT = 'WHAT YR WAS S FIRST TOLD ABOUT HRTA'
      ATTFLAG  = 'HRTA YR IS BEFORE IFUI YR'
      SINCEART = 'HAS S HAD ADDNL HRTA SINCE THEN'
      ATTKYR1  = 'YEAR OF FIRST ADDITIONAL ATTACK'
      ATTKYR2  = 'YEAR OF SECOND ADDITIONAL ATTACK'
      ATTKYR3  = 'YEAR OF THIRD ADDITIONAL ATTACK'
      ATTKYR4  = 'YEAR OF FOURTH ADDITIONAL ATTACK'
      ATTFL2_1 = 'FIRST ADDITIONAL ATTACK FLAG'
      ATTFL2_2 = 'SECOND ADDITIONAL ATTACK FLAG'
      ATTFL2_3 = 'THIRD ADDITIONAL ATTACK FLAG'
      ATTFL2_4 = 'FOURTH ADDITIONAL ATTACK FLAG'
      B23_HOSP = 'WAS S HODP FOR HEART ATTACK'
      B24_HOSP = 'WAS S HOSP FOR ANY OTH HEART COND'
      ADDBYPAS = 'ADDITIONAL BY-PASS SURGERY'
      CORONBYP = 'HAS S EVER HAD CORON BY-PASS SURG'
      B27_BYPS = 'WAS S HOSP FOR CORON BY-PASS SURG'
      PACEMAKR = 'HAD S EVER HAD PACEREPL'
      B29_PACE = 'HAD S BEEN HOSP FOR PACEREPL'
      ADDSTRKE = 'DOCTOR CONFIRMED ADDITIONAL CVA'
      CVA      = 'DOCTOR CONFIRMED CVA'
      STRKYR1  = 'WHAT YR WAS S FIRST TOLD OF STROKE'
      STRKFLAG = 'YEAR IS BEFORE PREVIOUS INTERVIEW'
      ADDISTRK = 'HAD S HAD ADDNL STROKE SINCE THEN'
      STYR2_1  = 'YEAR OF FIRST ADDITIONAL STROKE'
      STYR2_2  = 'YEAR OF SECOND ADDITIONAL STROKE'
      STFL2_1  = 'FIRST ADDITIONAL STROKE FLAG'
      STFL2_2  = 'SECOND ADDITIONAL STROKE FLAG'
      B35_HOSP = 'WAS S HOSPITALIZED FOR A STROKE'
      STRARMLG = 'WEAK ARM AND LEG DUE TO STROKE'
      STRWALK  = 'TROUBLE WALKING DUE TO STROKE'
      STRTALK  = 'TROUBLE TALKING DUE TO STROKE'
      STRTRBLE = 'OTHER TROUBLE DUE TO STROKE'
      CHECK1   = 'CAN PROXY COMPLETE SECTION B'
      DIABMED  = 'S TAKING MEDICATION FOR DIABETES'
      SUGRDIAB = 'DOCTOR CONFIRMED DIABETES'
      DIABYR1  = 'YEAR FIRST TOLD OF DIABETES'
      DIABFLAG = 'DIAB YR IS BEFORE IFUI YR'
      INSLNDB  = 'IS S TAKING INSULIN INJ FOR DIAB'
      ORALDB   = 'IS S TAKING ORAL MEDICATION FOR DIAB'
      B42_HOSP = 'WAS S HOSPITALIZED FOR DIABETES'
      HIGHBLCH = 'DID DR TELL S HAS HIGH BLD CHOLEST'
      BLCHMED  = 'MEDICINE'
      BLCHWIGT = 'WEIGHT'
      BLCHFTFD = 'FAT FOODS'
      BLCHCHFD = 'HIGH CHOLESTEROL FOODS'
      BLCHEXER = 'EXERCISE'
      CHMEDLW  = 'MEDICINE'
      CHWIGTLW = 'WEIGHT'
      CHFTFDLW = 'HIGH FAT FOODS'
      CHCHFDLW = 'HIGH CHOLESTEROL FOODS'
      CHEXERLW = 'EXERCISING'
      HBPMEDIC = 'HAS DR PRESCRIBED MEDICINE FOR HBP'
      HYPER    = 'DOCTOR CONFIRMED HYPERTENSION'
      HBPYEAR1 = 'WHAT YEAR WAS S FIRST TOLD ABOUT HBP'
      HIBPFLAG = 'YEAR ENTERED IS BEFORE PREVIOUS INT DATE'
      PRESCMED = 'HAS DR PRESCRIBED MEDICINE FOR HBP'
      MEDREGLR = 'DOES S TAKE MEDICINE CURRENTLY'
      HGBLWIGT = 'CONTROL WEIGHT'
      HGBLSALT = 'CUT DOWN SALT OR SODIUM'
      HGBLEXER = 'INCREASE EXERCISE'
      HBWIGTLW = 'CURRENTLY CONTROL WEIGHT'
      HBSALTLW = 'CURRENTLY CUT DOWN SALT AND SODIUM'
      HBEXERLW = 'CURRENTLY EXERCISE'
      B48_HIGH = 'WAS S HOSPITALIZED FOR HBP'
      BRCANYR  = 'YEAR TOLD HAD BREAST CANCER'
      CANCTYPE = 'HAS S HAD ANY OTHER CANCER'
      CANCRSRT = 'DOCTOR CONFIRMED CANCER OF ANY SORT'
      B52_CANC = 'WAS S HOSPITALIZED FOR ANY CANC COND'
      CANCCNT  = 'NUMBER OF CANCER SITES/TYPES S HAD'
      CHECK2   = 'CAN PROXY COMPLETE SECTION B'
      FRACHIP  = 'HAS S HAD ADDITIONAL FRACTURED HIP'
      BRKNHIP  = 'DOCTOR CONFIRMED FRACTURED HIP'
      HIPYEAR1 = 'WHAT YR WAS S FIRST TOLD OF FRAC HIP'
      HIPFLAG  = 'FRAC HIP YR IS BEFORE IFUI YR'
      ANTHRHIP = 'ADDITIONAL FRACTURED HIP'
      HIPYR2_1 = 'YEAR OF FIRST ADDTL HIP FRACTURE'
      HIPYR2_2 = 'YEAR OF SECOND ADDTL HIP FRACTURE'
      HIPYR2_3 = 'YEAR OF THIRD ADDTL HIP FRACTURE'
      HIPYR2_4 = 'YEAR OF FOURTH ADDTL HIP FRACTURE'
      HYRFL2_1 = 'FIRST ADDTL HIP FRACTURE FLAG'
      HYRFL2_2 = 'SECOND ADDTL HIP FRACTURE FLAG'
      HYRFL2_3 = 'THIRD ADDTL HIP FRACTURE FLAG'
      HYRFL2_4 = 'FOURTH ADDTL HIP FRACTURE FLAG'
      B61_HOSP = 'HOSPITALIZED FOR FRACTURED HIP'
      OSTEOPOR = 'S EVER HAVE OSTEOPOROSIS'
      OSTEOYR  = 'R TOLD OSTEOPOROSIS'
      ADBKWRST = 'ADDITIONAL BROKEN WRIST'
      BRKNWRST = 'DID S HAVE BROKEN WRIST'
      WRSTYR1  = 'YEAR OF FIRST ADDTL BROKEN WRIST'
      WRSTYR2  = 'YEAR OF SECOND ADDTL BROKEN WRIST'
      WRSTYR3  = 'YEAR OF THIRD ADDTL BORKEN WRIST'
      WRSTYR4  = 'YEAR OF FOURTH ADDTL BROKEN WRIST'
      FALLS    = 'ANY FALLS'
      NUMFALLS = 'NUMBER OF FALLS'
      FALLBKBN = 'BROKEN BONE FROM FALL'
      FALLHEAD = 'HEAD INJURY FROM FALL'
      FALLMEDC = 'MEDICAL HELP FROM FALL'
      B70_FALL = 'HOSPITALIZED FOR FALL'
      B71_FLU  = 'HOSPITALIZED FOR PNEUMONIA'
      KIDNYST  = 'ADDITIONAL KIDNEY DISEASE'
      EVERKDNY = 'EVER HAD A KIDNEY DISEASE'
      YRTELKID = 'YR FIRST TOLD OF KIDNEY DISEASE'
      KIDNEYFG = 'YR ENTERED IS BEFORE PREVIOUS INT DATE'
      DOCKID   = 'EVER HAD KIDNEY INFECTION'
      FRSTOLDK = 'YR FIRST TOLD HAD KIDNEY INFECTION'
      B74_HOSP = 'HOSPITALIZED FOR KIDNEY DISEASE'
      SURGCATR = 'ADDITIONAL CATARACT SURGERY'
      EVERCATR = 'EVER HAD CATARACTS'
      CATRSURG = 'EVER HAVE CATARACT SURGERY'
      YRCATR1  = 'YEAR OF FIRST CATARACT SURGERY'
      YRCATR2  = 'YEAR OF SECOND CATARACT SURGERY'
      CATFLAG1 = 'FIRST CATARACT SURGERY FLAG'
      CATFLAG2 = 'SECOND CATARACT SURGERY FLAG'
      B79_HOSP = 'HOSPITALIZED FOR CATARACT SURG'
      VASECTMY = 'EVER HAD VASECTOMY'
      AGEVASEC = 'AGE HAD VASECTOMY'
      B83_HOSP = 'HOSPITALIZED FOR ANY OTHER REASON'
      FACIL    = 'EVER STAYED AT A FACILITY'
      RESTCNT  = 'NUMBER OF REST SEGMENTS'
      HEALTH   = 'HEALTH CHANGES DURING LAST 12 MONTHS'
      PREVMNHT = 'HLTH CHANGE MO BEFORE NH OR DEATH'
      PREVYRHT = 'HLTH CHANGE YR BEFORE NH OR DEATH'
      SUBDIEHN = 'DIED IN HOSPITAL OR NURSING HOME'
      DTHCAUSE = 'CAUSE OF DEATH'
      SUBJCOND = 'DOCTOR CONFIRMED CAUSE OF DEATH'
      STAYBED  = 'STAY IN BED MOST OF DAY'
      GRLNGTHB = 'TIME PERIOD S WAS BEDRIDDEN'
      LNGTHBED = 'NUMBER OF MONTHS/YEARS BEDRIDDEN'
      C2UNIT   = 'TIME UNIT (MONTHS OR YEARS)'
      USELIMBS = 'PROBLEM THAT PREVENTS USE OF LIMB/S'
      PARALMB  = 'PARALYSIS OF LIMB/S'
      AMPUTLMB = 'AMPUTATION OF LIMB/S'
      ARTHLMB  = 'SEVERE ARTHRITIS OF LIMB/S'
      OTHLMB   = 'OTHER REASON PREVENTS USE OF LIMB/S'
      LIMBOTH1 = 'OTHER REASON'
      PARARUL  = 'PARALYSIS OF RIGHT ARM/HAND'
      PARALUL  = 'PARALYSIS OF LEFT ARM/HAND'
      PARARLL  = 'PAPALYSIS OF RIGHT LEG/FOOT'
      PARALLL  = 'PAPALYSIS OF LEFT LEG/FOOT'
      AMPUTRUL = 'AMPUTATION OF RIGHT ARM/HAND'
      AMPUTLUL = 'AMPUTATION OF LEFT ARM/HAND'
      AMPUTRLL = 'AMPUTATION OF RIGHT LEG/FOOT'
      AMPUTLLL = 'AMPUTATION OF LEFT LEG/FOOT'
      OTLMBRUL = 'INVOLVEMENT OF RIGHT ARM/HAND'
      OTLMBLUL = 'INVOLVEMENT OF LEFT ARM/HAND'
      OTLMBRLL = 'INVOLVEMENT OF RIGHT LEG/FOOT'
      OTLMBLLL = 'INVOLVEMENT OF LEFT LEG/FOOT'
      LIM_CONT = 'ACTIVITIES QUESTIONS DETERMINATOR'
      USEEQUIP = 'DOES S USE SPECIAL EQUIP'
      SPBATH   = 'DOES S USE DEVICES IN BATH'
      CANE     = 'DOES S USE CANE'
      ARTLIMBS = 'DOES S USE ARTIFICIAL LIMB'
      WALKER   = 'DOES S USE WALKER OR CRUTCHES'
      WHEELCHR = 'DOES S USE WHEELCHAIR'
      DEVICES  = 'DOES S USE DEVICES FOR DRESSING'
      SPCHAIR  = 'DOES S USE SPECIAL COMMODE'
      EATDEV   = 'DOES S USE EATING DEVICES'
      CFREQ    = 'ACTIVITIES QUESTIONS DETERMINATOR'
      C10A     = 'CAACTIV1!'
      C10B     = 'DIFFCLTY1!'
      C10C     = 'HELPPRSN1!'
      C10D     = 'HELPAID1!'
      C10E     = 'HELPDIFF1!'
      C11A     = 'CAACTIV2!'
      C11B     = 'DIFFCLTY2!'
      C11C     = 'HELPPRSN2!'
      C11D     = 'HELPAID2!'
      C11E     = 'HELPDIFF2!'
      C12A     = 'CAACTIV3!'
      C12B     = 'DIFFCLTY3!'
      C12C     = 'HELPPRSN3!'
      C12D     = 'HELPAID3!'
      C12E     = 'HELPDIFF3!'
      C13A     = 'CAACTIV4!'
      C13B     = 'DIFFCLTY4!'
      C13C     = 'HELPPRSN4!'
      C14A     = 'CAACTIV5!'
      C14B     = 'DIFFCLTY5!'
      C14C     = 'HELPPRSN5!'
      C15A     = 'CAACTIV6!'
      C15B     = 'DIFFCLTY6!'
      C15C     = 'HELPPRSN6!'
      C16A     = 'CAACTIV7!'
      C16B     = 'DIFFCLTY7!'
      C16C     = 'HELPPRSN7!'
      C17A     = 'CAACTIV8!'
      C17B     = 'DIFFCLTY8!'
      C17C     = 'HELPPRSN8!'
      C17D     = 'DIFFCLTY8!'
      C17E     = 'HELPDIFF8!'
      C18A     = 'CAACTIV9!'
      C18B     = 'DIFFCLTY9!'
      C18C     = 'HELPPRSN9!'
      C18D     = 'HELPAID9!'
      C18E     = 'HELPDIFF9!'
      C19A     = 'CAACTIV10!'
      C19B     = 'DIFFCLTY10!'
      C19C     = 'HELPPRSN10!'
      C19D     = 'HELPAID10!'
      C19E     = 'HEPLDIFF10!'
      C20A     = 'CAACTIV11!'
      C20B     = 'DIFFCLTY11!'
      C20C     = 'HELPPRSN11!'
      C20D     = 'HELPAID11!'
      C20E     = 'HELPDIFF11!'
      C21A     = 'CAACTIV12!'
      C21B     = 'DIFFCLTY12!'
      C21C     = 'HELPPRSN12!'
      C22A     = 'CAAVTIV13!'
      C22B     = 'DIFFCLTY13!'
      C22C     = 'HELPPRSN13!'
      C22D     = 'HELPAID13!'
      C22E     = 'HELPDIFF13!'
      C23A     = 'CAACTIV14!'
      C23B     = 'DIFFICLTY14!'
      C23C     = 'HELPPRSN14!'
      C24A     = 'CAACTIV15!'
      C24B     = 'DIFFCLTY15!'
      C24C     = 'HELPPRSN15!'
      C24D     = 'HELPAID15!'
      C24E     = 'HELPDIFF15!'
      C25A     = 'CAACTIV16!'
      C25B     = 'DIFFCLTY16!'
      C25C     = 'HELPPRSN16!'
      C25D     = 'HELPAID16!'
      C25E     = 'HELPDIFF16!'
      C26A     = 'CAACTIV17!'
      C26B     = 'DIFFCLTY17!'
      C26C     = 'HELPPRSN17!'
      C26D     = 'HELPAID17!'
      C26E     = 'HELPDIFF17!'
      C27A     = 'CAACTIV18!'
      C27B     = 'DIFFCLTY18!'
      C27C     = 'HELPPRSN18!'
      C28A     = 'CAACTIV19!'
      C28B     = 'DIFFCLTY19!'
      C28C     = 'HELPPRSN19!'
      C28D     = 'HELPAID19!'
      C28E     = 'HELPDIFF19!'
      C29A     = 'CAACTIV20!'
      C29B     = 'DIFFCLTY20!'
      C29C     = 'HELPPRSN20!'
      C30A     = 'CAACTIV21!'
      C30B     = 'DIFFCLTY21!'
      C30C     = 'HELPPRSN21!'
      C31A     = 'CAACTIV22!'
      C31B     = 'DIFFCLTY22!'
      C31C     = 'HELPPRSN22!'
      C32A     = 'CAACTIV23!'
      C32B     = 'DIFFCLTY23!'
      C32C     = 'HELPPRSN23!'
      RESPC    = 'ANOTHER PERSON TO ANSWER SECTION C'
      PRXSMDRD = 'PROXY CAN ANSWER SECTION D'
      SMOKE100 = 'EVER SMOKE 100 CIGARETTES A DAY'
      SMOKENOW = 'SMOKE CIGARETTES NOW'
      SMKPERDY = 'HOW MANY CIGARETTES SMOKED PER DAY'
      YRSSMOKE = 'NUMBER OF YEARS SMOKED CIGARETTES'
      GRMONTHS = 'WHEN DID S STOP SMOKING CIGARETTES'
      MONTHSTP = 'MONTH STOPPED SMOKING CIGARETTES'
      YEARSTOP = 'YEAR STOPPED SMOKING CIGARETTES'
      NUMBSMOK = 'NUMBER OF CIGARETTES SMOKED A DAY'
      DIDSMOKE = 'NUMBER OF YEARS SMOKED CIGARETTES'
      CSMKNOW  = 'DOES S SMOKE CIGARETTES NOW'
      CSMKPRDY = 'HOW MANY CIGARETTES SMOKED PER DAY'
      GRNCSMKM = 'WHEN S LAST STOP SMOKING CIGARETTES'
      NCSMKMO  = 'MONTH S STOPPED SMOKING'
      NCSMKYR  = 'YEAR S STOPPED SMOKING'
      DRINKYR  = 'IN THE PAST YEAR, HAD ONE DRINK'
      GROFTNBE = 'HOW OFTEN S DRINK BEER IN PAST YR'
      OFTNBEER = 'ON AVERAGE HOW OFTEN DRINKS BEER'
      WKMOBEER = 'TIME UNIT,BEER (WEEK OR MONTH)'
      NUMBBEER = 'NUMBER OF CANS OF BEER'
      GROFTNWI = 'HOW OFTEN S DRINK WINE IN PAST YR'
      OFTNWINE = 'ON AVERAGE HOW OFTEN DRINKS WINE'
      WKMOWINE = 'TIME UNIT, WINE (WEEK OR MONTH)'
      NUMBWINE = 'NUMBER OF GLASSES OF WINE'
      GROFTNLI = 'HOW OFTEN S DRINK LIQ&NUM OF SHOTS DAILY'
      OFTNLIQ  = 'ON AVERAGE HOW OFTEN DRINKS LIQUOR'
      WKMOLIQ  = 'TIME UNIT, LIQ (WEEK OR MONTH)'
      NUMBSHOT = 'NUMBER OF SHOTS OF LIQUOR'
      EXERPROG = 'DOES S EXERCISE REGULARLY'
      GRE2NUM  = 'MOS/YRS S EXERCISED/PLAYED SPORTS REG'
      E2NUM    = 'NUMBER OF MOS OR YRS REG EXERCISE'
      E2UNIT   = 'TIME UNIT REG EXERCISE (MONTH OR YR)'
      GRE3NUM  = 'HOW OFTEN ACTIVE EXERCISE/SPORTS'
      E3NUM    = 'HOW OFTEN DOES S EXERCISE'
      E3UNIT   = 'TIME UNIT EXERCISE (MONTH OR YR)'
      SPORTTIM = 'HOW MUCH TIME EXERCISE'
      GRE5NUM  = 'HOW OFTEN LIGHT PHYSICAL ACTIVITY'
      E5NUM    = 'HOW OFTEN LIGHT EXERCISE'
      E5UNIT   = 'TIME UNIT LIGHT EXERCISE (MO OR YR)'
      ACTVTIM  = 'HOW MUCH TIME LIGHT EXERCISE'
      WHTCOMPR = 'COMPARE CURRENT WEIGHT WITH 12 MO AGO'
      WEIGHNOW = 'PRESENT WEIGHT'
      GRSDIMEN = 'ADDITIONAL QUESTIONS ON S WEIGHT'
      SDIMENSN = 'SKINNY OR HEAVY WHEN YOUNG'
      SHEIGHT  = 'SHORT OR TALL WHEN YOUNG'
      SWGHT25  = 'USUAL WEIGHT AT AGE 25'
      SWGHT40  = 'USUAL WEIGHT AT AGE 40'
      SWGHT65  = 'USUAL WEIGHT AT AGE 65'
      WREYEGLS = 'WEAR EYEGLASSES OR CONCTACTS'
      SEESTR   = 'SEE FRIEND ACROSS STREET'
      SEEPRINT = 'SEE LETTERS IN ORDINARY PRINT'
      HEARAID  = 'EVER WORN A HEARING AID'
      HEARNORM = 'HEAR NORMAL VOICE ACROSS ROOM'
      WOHRGAID = 'HEAR NORMALLY WITHOUT HEARING AID'
      PRXPGMD  = 'PROXY CAN ANSWER SECTION G'
      EVERPREG = 'EVER PREGNANT'
      PREGNOW1 = 'IS S PREGNANT NOW'
      FRSTBRTH = 'AGE WHEN FIRST CHILD WAS BORN'
      SINCPREG = 'PREGNANT SINCE LAST INT'
      PREGNOW2 = 'IS S PREGNANT NOW'
      LASTBRTH = 'AGE WHEN LAST CHILD WAS BORN'
      LIVEBRTH = 'NUMBER OF LIVE BIRTHS'
      MISCARAG = 'EVER MISCARRIED'
      NUMMISS  = 'NUMBER OF MISCARRAIGES'
      HAVEWOMB = 'DOES S HAVE UTERUS'
      AGEREMVD = 'AGE WHEN UTERUS REMOVED'
      BOTHOVRY = 'DOES S HAVE BOTH OVARIES'
      ONEOVRY  = 'DOES S HAVE ONE OVARY'
      REMVOVRY = 'AGE WHEN LAST OVARY REMOVED'
      HAVPERD  = 'IS S STILL HAVING PERIODS'
      AGEPERD  = 'AGE WHEN HAD LAST PERIOD'
      PERDREG  = 'REGULAR PERIODS'
      CHNGLIFE = 'WHY IRREGULAR'
      HORMONE  = 'HORMONE PILLS TAKEN'
      AGEHPILL = 'AGE LAST TOOK HORMONE PILLS'
      GRG20UNI = 'LONGEST PRD OF TIME S CONT. TOOK HP'
      G20UNITA = 'TIME TOOK H PILLS CONTINUOUSLY'
      HPIL1MOL = 'NUM OF MONTHS CONTINUOUSLY TOOK HP'
      HPIL1YRL = 'NUM OF YEARS CONTINUOUSLY TOOK HP'
      G20ATOT  = 'TOTAL NUMBER OF MONTHS'
      GRG20    = 'YRS/MOS DID S ACTUALLY USE HORMONE PILLS'
      G20UNITB = 'TIME H PILLS ACTUALLY TAKEN'
      HPIL1MOT = 'TOTAL MONTHS TOOK HORMONE PILLS'
      HPIL1YRT = 'TOTAL YRS TOOK HORMONE PILLS'
      G20BTOT  = 'TOTAL NUMBER OF MONTHS'
      PILLCHNG = 'EVER TAKE HORMONE PILLS'
      GRG22UNI = 'TIME PERIOD S CONT. TOOK HORMONE PILLS'
      G22UNITA = 'TIME TOOK H PILLS CONTINUOUSLY'
      HPIL2MOL = 'MONTHS CONINUOUSLY TOOK HORMONE PIL'
      HPIL2YRL = 'YRS CONTINUOUSLY TOOK HORMONE PILLS'
      G22ATOT  = 'TOTAL NUMBER OF MONTHS'
      GRG22UNB = 'YRS OR MOS S ACTUALLY USED HORMONE PILLS'
      G22UNITB = 'TIME H PILLS ACTUALLY TAKEN'
      HPIL2MOT = 'TOTAL MONTHS TOOK HORMONE PILLS'
      HPIL2YRT = 'TOTAL YRS TOOK HORMONE PILLS'
      G22BTOT  = 'TOTAL NUMBER OF MONTHS'
      CURTAKHM = 'CURRENTLY TAKING HORMONE PILLS'
      COLORPIL = 'WHAT COLOR PILL'
      GRUNIT25 = 'PRD OF TIME S TOOK SAME COLOR PILL'
      UNIT25   = 'TIME UNIT'
      LONGCOLR = 'HOW LONG TAKEN THIS COLOR PILL'
      PROVERA  = 'DOES S TAKE PROVERA'
      CURPROV  = 'CURRENTLY TAKING PROVERA'
      GRUNIT28 = 'PRD OF TIME S TOOK PROGESTIN (PROV)'
      UNIT28   = 'TIME PERIOD'
      LONGPIL2 = 'HOW LONG TAKEN PROVERA'
      BRTHPILL = 'BIRTH CONTROL PILLS TAKEN'
      AGELASTP = 'AGE LAST TOOK BIRTH CONTROL PILLS'
      GRG31UNI = 'LONGEST PERIOD OF TIME S CONT TOOK BCP'
      G31UNITA = 'TIME TOOK BC PILLS CONTINUOUSLY'
      BPIL1MOL = 'MONTHS CONT. TOOK BCP'
      BPIL1YRL = 'YEARS CONT. TOOK BCP'
      G31ATOT  = 'TOTAL NUMBER OF MONTHS'
      GRG31UNB = 'YRS OR MOS S ACTUALLY USED BCP'
      G31UNITB = 'TIME BC PILLS ACTUALLY TAKEN'
      BPIL1MOT = 'TOTAL MONTHS TOOK BCP'
      BPIL1YRT = 'TOTAL YEARS TOOK BCP'
      G31BTOT  = 'TOTAL NUMBER OF MONTHS'
      BRTHPIL2 = 'EVER TOOK BIRTH CONTROL PILLS'
      AGEFRSTP = 'AGE FIRST TOOK BIRTH CONTROL PILLS'
      CURPILL  = 'CURRENTLY TAKING BIRTH CONTROL PILLS'
      AGELSTP2 = 'AGE LAST TOOK BIRTH CONTROL PILLS'
      GRG36UNA = 'LONGEST PRD OF TIME S CONT TOOK BCP'
      G36UNITA = 'TIME TOOK BC PILLS CONTINUOUSLY'
      BPIL2MOL = 'MO CONT TOOK BIRTH CONTROL PILLS'
      BPIL2YRL = 'YRS CONT TOOK BIRTH CONTROL PILL'
      G36ATOT  = 'TOTAL NUMBER OF MONTHS'
      GRG36UNB = 'YEARS OR MOS S ACTUALLY USED BCP'
      G36UNITB = 'TIME BC PILLS ACTUALLY TAKEN'
      BPIL2MOT = 'TOTAL MON TOOK BIRTH CONTROL PILLS'
      BPIL2YRT = 'TOTAL YRS TOOK BIRTH CONTROL PILLS'
      G36BTOT  = 'TOTAL NUMBER OF MONTHS'
      GRG37UNI = 'YRS OR MOS S USE BCP BEFORE 25'
      G37UNIT  = 'TIME UNIT (YRS & MOS) USE BCP BFR 25'
      BPIL25MO = 'TOTAL MONTHS TOOK BIRTH CONTROL PILL'
      BPIL25YR = 'YRS TOOK BCP BEFORE 25'
      BEFCHILD = 'BCP BEFORE FIRST CHILD'
      GRG39UNI = 'YRS OR MOS FRST CHILD WAS BORN S USE BCP'
      G39UNIT  = 'TIME UNIT USED BCP BFR FIRST BIRTH'
      BPILBCMO = 'MONTHS TOOK BCP BEFORE FIRST CHILD'
      BPILBCYR = 'YRS TOOK BCP BEFORE FIRST CHILD'
      TUBETYD  = 'EVER HAD TUBES TIED'
      AGETUBTY = 'AGE TUBES TIED'
      CALCIUM  = 'EVER TOOK CALCIUM'
      GRG43UNI = 'PERIOD OF TIME S TOOK CALCIUM REG'
      UNIT43   = 'TIME UNIT'
      LONGCALC = 'HOW LONG TOOK CALCIUM'
      PAPTEST  = 'EVER HAD PAP TEST'
      LONGPAP  = 'HOW LONG SINCE PAP TEST (YRS)'
      MANYPAP5 = 'HOW MANY PAP TESTS IN LAST 5 YRS'
      BRSTEXAM = 'DR EVER EXAMINED BREASTS'
      NUMBRST5 = 'NUM OF EXAMS IN LAST 5 YRS'
      LONGBRST = 'HOW LONG SINCE BREAST EXAM (YRS)'
      EXAMSELF = 'KNOW HOW TO SELF-EXAM BREASTS'
      EVEREXAM = 'HAS S EXAMINED BREASTS'
      OFTNEXAM = 'HOW OFTEN EXAM BREASTS A YEAR'
      MAMMO    = 'EVER HAD A MAMMOGRAM'
      NUMMAMO5 = 'NUM TIMES HAD MAMMOGRAM IN LST 5 YRS'
      LASTMAMO = 'WHEN DID S HAVE LAST MAMMOGRAM'
      MEDICARE = 'IS S COVERED BY MEDICARE'
      HHCF     = 'WERE THERE HOSPTLIZATIONS ON HHCF CHART'
      RELAPRX1 = 'R RELATIONSHIP TO S'
      SUBAST   = 'DID SUBJ RECEIVE ASSISTANCE W/INTERVW'
      NUMAST   = 'NUMBER OF ASSISTANTS'
      AST1REL  = '1ST ASSISTANT RELATIONSHIP TO SUBJ'
      PRIMAST  = 'WAS SUBJECT OR ASST PRIMARY RESPONDT'
      GRKHEAR  = 'REASONS FOR HELP FROM ASSISTANT OR PROXY'
      KHEAR    = 'HEARING REASON FOR HELP'
      KSPEECH  = 'SPEECH REASON FOR HELP'
      KLANGU   = 'LANGUAGE REASON FOR HELP'
      KMEMRY   = 'MEMORY, SENILITY REASON FOR HELP'
      KINSTIT  = 'INSTITUTIONALIZATION REASON FOR HELP'
      KALZH    = 'ALZHEIMER REASON FOR HELP'
      KOTHMENT = 'OTH MENTAL CONDITION REASON FOR HELP'
      KOTHPHY  = 'OTHR PHYSICAL ILLNESS REASON FOR HELP'
      KOTHHEAL = 'OTHER NON-HEALTH REASON FOR HELP'
      KOTHER   = 'OTHER REASON FOR HELP'
      INFOSATS = 'INFO FROM SUBJECT/PROXY SATISFACTORY'
      SUBAWARE = 'DESCRIBE SUBJECT AWARENESS LEVEL'
      QHELDATT = 'R ATTENTION HELD'
      QUPSTDEP = 'R UPSET OR DEPRESSED'
      QBORING  = 'R BORED OR UNINTERESTED'
      RCAPABLE = 'R INTELLECTUALLY CAPABLE'
      RACCURTE = 'R ANSWERS REASONABLY ACCURATE'
      RUNDESST = 'R UNDERSTOOD THE QUESTIONS'
      BADSECT  = 'WAS THERE AN UPSETTING SECTION'
      RHRDHRNG = 'R HARD OF HEARING'
      QINTSPAN = 'INTERVIEW CONDUCTED IN SPANISH'
      GRCANC1  = 'TYPES OF CA REPORTED FOR S BY R'
      CANCNUM1 = 'FREQUENCY COUNT FLAG'
      CACRLOC1 = 'WHERE WAS CANCER/WHAT TYPE WAS IT'
      IC9CANC1 = 'ICD9 CODE FOR CANCER'
      ANYCANC1 = 'ANY OTHER TYPES OF CANCER'
      TODCANC1 = 'YEAR S FIRST TOLD ABOUT CANCER'
      CANCFL1  = 'CA YR IS BEFORE IFUI YR'
      B5_HOSP1 = 'WAS S HOSPITALIZED FOR CANCER'
      CANCNUM2 = 'FREQUENCY COUNT FLAG'
      CACRLOC2 = 'WHERE WAS CANCER/WHAT TYPE WAS IT'
      IC9CANC2 = 'ICD9 CODE FOR CANCER'
      ANYCANC2 = 'ANY OTHER TYPES OF CANCER'
      TODCANC2 = 'YEAR S FIRST TOLD ABOUT CANCER'
      CANCFL2  = 'CA YR IS BEFORE IFUI YR'
      B5_HOSP2 = 'WAS S HOSPITALIZED FOR CANCER'
      CANCNUM3 = 'FREQUENCY COUNT FLAG'
      CACRLOC3 = 'WHERE WAS CANCER/WHAT TYPE WAS IT'
      IC9CANC3 = 'ICD9 CODE FOR CANCER'
      ANYCANC3 = 'ANY OTHER TYPES OF CANCER'
      TODCANC3 = 'YEAR S FIRST TOLD ABOUT CANCER'
      CANCFL3  = 'CA YR IS BEFORE IFUI YR'
      B5_HOSP3 = 'WAS S HOSPITALIZED FOR CANCER'
      CANCNUM4 = 'FREQUENCY COUNT FLAG'
      CACRLOC4 = 'WHERE WAS CANCER/WHAT TYPE WAS IT'
      IC9CANC4 = 'ICD9 CODE FOR CANCER'
      ANYCANC4 = 'ANY OTHER TYPES OF CANCER'
      TODCANC4 = 'YEAR S FIRST TOLD ABOUT CANCER'
      CANCFL4  = 'CA YR IS BEFORE IFUI YR'
      B5_HOSP4 = 'WAS S HOSPITALIZED FOR CANCER'
      CANCNUM5 = 'FREQUENCY COUNT FLAG'
      CACRLOC5 = 'WHERE WAS CANCER/WHAT TYPE WAS IT'
      IC9CANC5 = 'ICD9 CODE FOR CANCER'
      ANYCANC5 = 'ANY OTHER TYPES OF CANCER'
      TODCANC5 = 'YEAR S FIRST TOLD ABOUT CANCER'
      CANCFL5  = 'CA YR IS BEFORE IFUI YR'
      B5_HOSP5 = 'WAS S HOSPITALIZED FOR CANCER'
      CANCNUM6 = 'FREQUENCY COUNT FLAG'
      CACRLOC6 = 'WHERE WAS CANCER/WHAT TYPE WAS IT'
      IC9CANC6 = 'ICD9 CODE FOR CANCER'
      ANYCANC6 = 'ANY OTHER TYPES OF CANCER'
      TODCANC6 = 'YEAR S FIRST TOLD ABOUT CANCER'
      CANCFL6  = 'CA YR IS BEFORE IFUI YR'
      B5_HOSP6 = 'WAS S HOSPITALIZED FOR CANCER'
      RESTNUM1 = 'FREQUENCY COUNT FLAG'
      ADSNPLC1 = 'TYPE OF FACILITY'
      ENERFRM1 = 'PLACE FROM WHICH ENTERED FACILITY'
      YERENTR1 = 'YEAR ENTERED FACILITY'
      NUSCARE1 = 'REQUIRED SKILLED NURSING CARE'
      SUGRECP1 = 'RECUPERATING FROM SURGERY'
      NEDHELP1 = 'NEEDED HELP WITH BATH, EAT, DRESS'
      RESPCMD1 = 'REQUIRED MEDICAL OR PHYSICAL THERAPY'
      COFUSED1 = 'TOO CONFUSED TO LIVE INDEPENDENTLY'
      CNDTNM11 = 'FIRST REASON FOR ENTERING NH'
      CNDTNM21 = 'SECOND REASON FOR ENTERING NH'
      CNDTNM31 = 'THIRD REASON FOR ENTERING NH'
      CNDTNM41 = 'FOURTH REASON FOR ENTERING NH'
      CNDTNM51 = 'FIFTH REASON FOR ENTERING NH'
      RECODE11 = 'DID S HAVE ALZHEIMER DISEASE'
      RECODE21 = 'DID S HAVE CANCER'
      RECODE31 = 'DID S HAVE DEPRESSION'
      RECODE41 = 'WAS S FRAIL/OLD'
      RECODE51 = 'DID S HAVE HARDENING OF ARTERIES'
      RECODE61 = 'WAS S INCONTINENT'
      RECODE71 = 'NO MEDICAL CONDITION'
      RECODE81 = 'WAS S SENILE'
      RECODE91 = 'DID S HAVE STROKE'
      REODE101 = 'DID S HAVE ALCOHOLISM'
      REODE111 = 'DID S HAVE ARTHRITIS'
      REODE121 = 'DISRUPTIVE BEHAVIOR'
      REODE131 = 'FRACTURE OTHER THAN HIP'
      REODE141 = 'DID S HAVE HEART ATTACK/OTH HEART COND'
      REODE151 = 'DID S HAVE HIP FRACTURE'
      REODE161 = 'DID S HAVE MENTAL ILLNESS'
      REODE171 = 'DID S HAVE OSTEOPOROSIS'
      REODE181 = 'DID S HAVE PARKINSON DISEASE'
      REODE191 = 'DID S HAVE OTHER-SPECIFIED DISEASE'
      B92NUM1  = 'LENGTH OF STAY'
      B92UNIT1 = 'TIME UNIT (WEEKS, MONTHS OR YEARS)'
      OTADMSN1 = 'ANY OTHER ADMISSIONS'
      RESTNUM2 = 'FREQUENCY COUNT FLAG'
      ADSNPLC2 = 'TYPE OF FACILITY'
      ENERFRM2 = 'PLACE FROM WHICH ENTERED FACILITY'
      YERENTR2 = 'YEAR ENTERED FACILITY'
      NUSCARE2 = 'REQUIRED SKILLED NURSING CARE'
      SUGRECP2 = 'RECUPERATING FROM SURGERY'
      NEDHELP2 = 'NEEDED HELP WITH BATH, EAT, DRESS'
      RESPCMD2 = 'REQUIRED MEDICAL OR PHYSICAL THERAPY'
      COFUSED2 = 'TOO CONFUSED TO LIVE INDEPENDENTLY'
      CNDTNM12 = 'FIRST REASON FOR ENTERING NH'
      CNDTNM22 = 'SECOND REASON FOR ENTERING NH'
      CNDTNM32 = 'THIRD REASON FOR ENTERING NH'
      CNDTNM42 = 'FOURTH REASON FOR ENTERING NH'
      CNDTNM52 = 'FIFTH REASON FOR ENTERING NH'
      RECODE12 = 'DID S HAVE ALZHEIMER DISEASE'
      RECODE22 = 'DID S HAVE CANCER'
      RECODE32 = 'DID S HAVE DEPRESSION'
      RECODE42 = 'WAS S FRAIL/OLD'
      RECODE52 = 'DID S HAVE HARDENING OF ARTERIES'
      RECODE62 = 'WAS S INCONTINENT'
      RECODE72 = 'NO MEDICAL CONDITION'
      RECODE82 = 'WAS S SENILE'
      RECODE92 = 'DID S HAVE STROKE'
      REODE102 = 'DID S HAVE ALCOHOLISM'
      REODE112 = 'DID S HAVE ARTHRITIS'
      REODE122 = 'DISRUPTIVE BEHAVIOR'
      REODE132 = 'FRACTURE OTHER THAN HIP'
      REODE142 = 'DID S HAVE HEART ATTACK/OTH HEART COND'
      REODE152 = 'DID S HAVE HIP FRACTURE'
      REODE162 = 'DID S HAVE MENTAL ILLNESS'
      REODE172 = 'DID S HAVE OSTEOPOROSIS'
      REODE182 = 'DID S HAVE PARKINSON DISEASE'
      REODE192 = 'DID S HAVE OTHER-SPECIFIED DISEASE'
      B92NUM2  = 'LENGTH OF STAY'
      B92UNIT2 = 'TIME UNIT (WEEKS, MONTHS OR YEARS)'
      OTADMSN2 = 'ANY OTHER ADMISSIONS'
      SAMEREA2 = 'SEC. ADMISSION SAME AS FIRST ADMISSION'
      RESTNUM3 = 'FREQUENCY COUNT FLAG'
      ADSNPLC3 = 'TYPE OF FACILITY'
      ENERFRM3 = 'PLACE FROM WHICH ENTERED FACILITY'
      YERENTR3 = 'YEAR ENTERED FACILITY'
      NUSCARE3 = 'REQUIRED SKILLED NURSING CARE'
      SUGRECP3 = 'RECUPERATING FROM SURGERY'
      NEDHELP3 = 'NEEDED HELP WITH BATH, EAT, DRESS'
      RESPCMD3 = 'REQUIRED MEDICAL OR PHYSICAL THERAPY'
      COFUSED3 = 'TOO CONFUSED TO LIVE INDEPENDENTLY'
      CNDTNM13 = 'FIRST REASON FOR ENTERING NH'
      CNDTNM23 = 'SECOND REASON FOR ENTERING NH'
      CNDTNM33 = 'THIRD REASON FOR ENTERING NH'
      CNDTNM43 = 'FOURTH REASON FOR ENTERING NH'
      CNDTNM53 = 'FIFTH REASON FOR ENTERING NH'
      RECODE13 = 'DID S HAVE ALZHEIMER DISEASE'
      RECODE23 = 'DID S HAVE CANCER'
      RECODE33 = 'DID S HAVE DEPRESSION'
      RECODE43 = 'WAS S FRAIL/OLD'
      RECODE53 = 'DID S HAVE HARDENING OF ARTERIES'
      RECODE63 = 'WAS S INCONTINENT'
      RECODE73 = 'NO MEDICAL CONDITION'
      RECODE83 = 'WAS S SENILE'
      RECODE93 = 'DID S HAVE STROKE'
      REODE103 = 'DID S HAVE ALCOHOLISM'
      REODE113 = 'DID S HAVE ARTHRITIS'
      REODE123 = 'DISRUPTIVE BEHAVIOR'
      REODE133 = 'FRACTURE OTHER THAN HIP'
      REODE143 = 'DID S HAVE HEART ATTACK/OTH HEART COND'
      REODE153 = 'DID S HAVE HIP FRACTURE'
      REODE163 = 'DID S HAVE MENTAL ILLNESS'
      REODE173 = 'DID S HAVE OSTEOPOROSIS'
      REODE183 = 'DID S HAVE PARKINSON DISEASE'
      REODE193 = 'DID S HAVE OTHER-SPECIFIED DISEASE'
      B92NUM3  = 'LENGTH OF STAY'
      B92UNIT3 = 'TIME UNIT (WEEKS, MONTHS OR YEARS)'
      OTADMSN3 = 'ANY OTHER ADMISSIONS'
      RESTNUM4 = 'FREQUENCY COUNT FLAG'
      ADSNPLC4 = 'TYPE OF FACILITY'
      ENERFRM4 = 'PLACE FROM WHICH ENTERED FACILITY'
      YERENTR4 = 'YEAR ENTERED FACILITY'
      NUSCARE4 = 'REQUIRED SKILLED NURSING CARE'
      SUGRECP4 = 'RECUPERATING FROM SURGERY'
      NEDHELP4 = 'NEEDED HELP WITH BATH, EAT, DRESS'
      RESPCMD4 = 'REQUIRED MEDICAL OR PHYSICAL THERAPY'
      COFUSED4 = 'TOO CONFUSED TO LIVE INDEPENDENTLY'
      CNDTNM14 = 'FIRST REASON FOR ENTERING NH'
      CNDTNM24 = 'SECOND REASON FOR ENTERING NH'
      CNDTNM34 = 'THIRD REASON FOR ENTERING NH'
      CNDTNM44 = 'FOURTH REASON FOR ENTERING NH'
      CNDTNM54 = 'FIFTH REASON FOR ENTERING NH'
      RECODE14 = 'DID S HAVE ALZHEIMER DISEASE'
      RECODE24 = 'DID S HAVE CANCER'
      RECODE34 = 'DID S HAVE DEPRESSION'
      RECODE44 = 'WAS S FRAIL/OLD'
      RECODE54 = 'DID S HAVE HARDENING OF ARTERIES'
      RECODE64 = 'WAS S INCONTINENT'
      RECODE74 = 'NO MEDICAL CONDITION'
      RECODE84 = 'WAS S SENILE'
      RECODE94 = 'DID S HAVE STROKE'
      REODE104 = 'DID S HAVE ALCOHOLISM'
      REODE114 = 'DID S HAVE ARTHRITIS'
      REODE124 = 'DISRUPTIVE BEHAVIOR'
      REODE134 = 'FRACTURE OTHER THAN HIP'
      REODE144 = 'DID S HAVE HEART ATTACK/OTH HEART COND'
      REODE154 = 'DID S HAVE HIP FRACTURE'
      REODE164 = 'DID S HAVE MENTAL ILLNESS'
      REODE174 = 'DID S HAVE OSTEOPOROSIS'
      REODE184 = 'DID S HAVE PARKINSON DISEASE'
      REODE194 = 'DID S HAVE OTHER-SPECIFIED DISEASE'
      B92NUM4  = 'LENGTH OF STAY'
      B92UNIT4 = 'TIME UNIT (WEEKS, MONTHS OR YEARS)'
      OTADMSN4 = 'ANY OTHER ADMISSIONS'
      RESTNUM5 = 'FREQUENCY COUNT FLAG'
      ADSNPLC5 = 'TYPE OF FACILITY'
      ENERFRM5 = 'PLACE FROM WHICH ENTERED FACILITY'
      YERENTR5 = 'YEAR ENTERED FACILITY'
      NUSCARE5 = 'REQUIRED SKILLED NURSING CARE'
      SUGRECP5 = 'RECUPERATING FROM SURGERY'
      NEDHELP5 = 'NEEDED HELP WITH BATH, EAT, DRESS'
      RESPCMD5 = 'REQUIRED MEDICAL OR PHYSICAL THERAPY'
      COFUSED5 = 'TOO CONFUSED TO LIVE INDEPENDENTLY'
      CNDTNM15 = 'FIRST REASON FOR ENTERING NH'
      CNDTNM25 = 'SECOND REASON FOR ENTERING NH'
      CNDTNM35 = 'THIRD REASON FOR ENTERING NH'
      CNDTNM45 = 'FOURTH REASON FOR ENTERING NH'
      CNDTNM55 = 'FIFTH REASON FOR ENTERING NH'
      RECODE15 = 'DID S HAVE ALZHEIMER DISEASE'
      RECODE25 = 'DID S HAVE CANCER'
      RECODE35 = 'DID S HAVE DEPRESSION'
      RECODE45 = 'WAS S FRAIL/OLD'
      RECODE55 = 'DID S HAVE HARDENING OF ARTERIES'
      RECODE65 = 'WAS S INCONTINENT'
      RECODE75 = 'NO MEDICAL CONDITION'
      RECODE85 = 'WAS S SENILE'
      RECODE95 = 'DID S HAVE STROKE'
      REODE105 = 'DID S HAVE ALCOHOLISM'
      REODE115 = 'DID S HAVE ARTHRITIS'
      REODE125 = 'DISRUPTIVE BEHAVIOR'
      REODE135 = 'FRACTURE OTHER THAN HIP'
      REODE145 = 'DID S HAVE HEART ATTACK/OTH HEART COND'
      REODE155 = 'DID S HAVE HIP FRACTURE'
      REODE165 = 'DID S HAVE MENTAL ILLNESS'
      REODE175 = 'DID S HAVE OSTEOPOROSIS'
      REODE185 = 'DID S HAVE PARKINSON DISEASE'
      REODE195 = 'DID S HAVE OTHER-SPECIFIED DISEASE'
      B92NUM5  = 'LENGTH OF STAY'
      B92UNIT5 = 'TIME UNIT (WEEKS, MONTHS OR YEARS)'
      OTADMSN5 = 'ANY OTHER ADMISSIONS'
      RESTNUM6 = 'FREQUENCY COUNT FLAG'
      ADSNPLC6 = 'TYPE OF FACILITY'
      ENERFRM6 = 'PLACE FROM WHICH ENTERED FACILITY'
      YERENTR6 = 'YEAR ENTERED FACILITY'
      NUSCARE6 = 'REQUIRED SKILLED NURSING CARE'
      SUGRECP6 = 'RECUPERATING FROM SURGERY'
      NEDHELP6 = 'NEEDED HELP WITH BATH, EAT, DRESS'
      RESPCMD6 = 'REQUIRED MEDICAL OR PHYSICAL THERAPY'
      COFUSED6 = 'TOO CONFUSED TO LIVE INDEPENDENTLY'
      CNDTNM16 = 'FIRST REASON FOR ENTERING NH'
      CNDTNM26 = 'SECOND REASON FOR ENTERING NH'
      CNDTNM36 = 'THIRD REASON FOR ENTERING NH'
      CNDTNM46 = 'FOURTH REASON FOR ENTERING NH'
      CNDTNM56 = 'FIFTH REASON FOR ENTERING NH'
      RECODE16 = 'DID S HAVE ALZHEIMER DISEASE'
      RECODE26 = 'DID S HAVE CANCER'
      RECODE36 = 'DID S HAVE DEPRESSION'
      RECODE46 = 'WAS S FRAIL/OLD'
      RECODE56 = 'DID S HAVE HARDENING OF ARTERIES'
      RECODE66 = 'WAS S INCONTINENT'
      RECODE76 = 'NO MEDICAL CONDITION'
      RECODE86 = 'WAS S SENILE'
      RECODE96 = 'DID S HAVE STROKE'
      REODE106 = 'DID S HAVE ALCOHOLISM'
      REODE116 = 'DID S HAVE ARTHRITIS'
      REODE126 = 'DISRUPTIVE BEHAVIOR'
      REODE136 = 'FRACTURE OTHER THAN HIP'
      REODE146 = 'DID S HAVE HEART ATTACK/OTH HEART COND'
      REODE156 = 'DID S HAVE HIP FRACTURE'
      REODE166 = 'DID S HAVE MENTAL ILLNESS'
      REODE176 = 'DID S HAVE OSTEOPOROSIS'
      REODE186 = 'DID S HAVE PARKINSON DISEASE'
      REODE196 = 'DID S HAVE OTHER-SPECIFIED DISEASE'
      B92NUM6  = 'LENGTH OF STAY'
      B92UNIT6 = 'TIME UNIT (WEEKS, MONTHS OR YEARS)'
      OTADMSN6 = 'ANY OTHER ADMISSIONS'
      HCFSR01  = 'ONE STAY RECORD 86 NHEFS-ARTHRITIS'
      HCFSR02  = 'ONE STAY RECORD 86 NHEFS-GOUT'
      HCFSR03  = 'ONE STAY RECORD 86 NHEFS-HEART ATTACK'
      HCFSR04  = 'ONE STAY RECORD 86 NHEFS-HEART COND'
      HCFSR05  = 'ONE STAY 86 NHEFS-CORONARY BYPASS SURG'
      HCFSR06  = 'ONE STAY RECORD 86 NHEFS-PACEMAKER'
      HCFSR08  = 'ONE STAY RECORD 86 NHEFS-STROKE/CVA'
      HCFSR09  = 'ONE STAY RECORD 86 NHEFS-DIABETES'
      HCFSR10  = 'ONE STAY 86 NHEFS-HIGH BLOOD PRESSURE'
      HCFSR11  = 'ONE STAY RECORD 86 NHEFS-SKIN CANCER'
      HCFSR12  = 'ONE STAY RECORD 86 NHEFS-FRACTURED HIP'
      HCFSR13  = 'ONE STAY RECORD 86 NHEFS-OTHER FRAC'
      HCFSR15  = 'ONE STAY RECORD 86 NHEFS-SURGERY'
      HCFSR16  = 'ONE STAY RECORD 86 NHEFS-DO NOT KNOW'
      HCFSR17  = 'ONE STAY 86 NHEFS-NOT ASCERTAINED'
      HCFSR18  = 'ONE STAY 86 NHEFS-TESTS/OBSERVATION/EXAM'
      HCFSR19  = 'ONE STAY 86 NHEFS-DIGESTIVE/ENDOCRINE'
      HCFSR20  = 'ONE STAY 86 NHEFS-RESPIRATORY'
      HCFSR21  = 'ONE STAY RECORD 86 NHEFS-INFECTION'
      HCFSR22  = 'ONE STAY 86 NHEFS-KIDNEY/BLADDER/URINARY'
      HCFSR23  = 'ONE STAY RECORD 86 NHEFS-DEBILITY/PAIN'
      HCFSR24  = 'ONE STAY 86 NHEFS-MALE REPRODUCTIVE COND'
      HCFSR25  = 'ONE STAY 86 NHEFS-MUSCULOSKELETAL/INJURY'
      HCFSR26  = 'ONE STAY RECORD 86 NHEFS-CIRCULATORY'
      HCFSR27  = 'ONE STAY 86 NHEFS-FEMALE REPRODUCTIVE'
      HCFSR28  = 'ONE STAY RECORD 86 NHEFS-MENTAL ILLNESS'
      HCFSR29  = 'ONE STAY RECORD 86 NHEFS-NEUROLOGIC'
      HCFSR30  = 'ONE STAY 86 NHEFS-NUTRITION/DEHYDRATION'
      HCFSR31  = 'ONE STAY 86 NHEFS-BLEEDING/BLOOD DIS'
      HCFSR32  = 'ONE STAY RECORD 86 NHEFS-SKIN CONDITION'
      HCFSR33  = 'ONE STAY 86 NHEFS-CONDITION NOT CODED'
      HCFSR34  = 'ONE STAY 86 NHEFS-NURS HOME ADMISSION'
      HCFSR35  = 'ONE STAY 86 NHEFS-HOSPITALIZED AT DEATH'
      HCFSR36  = 'ONE STAY RECORD 86 NHEFS-EYE DISORDERS'
      HCFSR37  = 'ONE STAY RECORD 86 NHEFS-FALLS'
      CAUSEDTH = 'UNDERLYING CAUSE OF DEATH'
      STRATUM  = 'STRATUM'
      PSU      = 'PSEUDO PRIMARY SAMPLING UNIT'
      SUBSAMPL = 'NHANES I SUBSAMPLE'
      SWGT1    = 'DETAILED SAMPLE PERSONS--LOCATION 1-35'
      SWGT2    = 'ALL SAMPLE PERSONS--LOCATION 1-35'
      SWGT3    = 'DETAILED SAMPLE PERSONS--LOCATION 1-65'
      SWGT4    = 'ALL SAMPLE PERSONS--LOCATION 1-65'
      SWGT5    = 'DETAILED SAMPLE PERSONS--LOCATION 66-100'
      SWGT6    = 'DETAILED SAMPLE PERSONS--LOCATION 1-100'
      ;
              



RUN;
